### ISSUE TITLE
Exodus Makefile.standalone

### ISSUE THREAD

**Issue by 3rav** [gsjaardema/seacas#101]
Where I can find Makefile.standalone from:

README
"3. Makefile.standalone.  Edit the top-level Makefile.standalone file
   and specify the compiler and other options as detailed in the
   file. Then, do "make -f Makefile.standalone"."

**Comment by gdsjaar** [comment]
Sorry, that is left over from a previous time…. I will clean that up.  Currently, the information in the top-level README.md must be used:

## Exodus
If you only want the exodus library, then follow most of the above instructions with the following exceptions:

  * You can either clone entire source tree as above, or you can
        download a zip file containing only the exodus source (and
        build-related files).  The url for the zip file is
        <https://github.com/gsjaardema/seacas/archive/exodus.zip>.
  * You only need the netcdf and optionally hdf5 libraries
  * Use the `cmake-exodus` file instead of `cmake-config`.
  * This will build, by default, a shared exodus library and also install the exodus.py Python interface.

I would recommend cloning the entire SEACAS source tree since the zip file exodus source is somewhat behind the current git repo source.
..Greg

**Comment by gsjaardema** [comment]
See the section "Configure, Build, and Install SEACAS" in the explanation at https://github.com/gsjaardema/seacas.  If you only want Exodus, then replace the step below where it says `enter the command ../cmake-config` with `enter the command ../cmake-exodus`

```
Configure, Build, and Install SEACAS
At this time, you should have all external TPL libraries built and installed into ${ACCESS}/lib and ${ACCESS}/include. You are now ready to configure the SEACAS CMake build.

cd $ACCESS
mkdir build
cd build
edit the ${ACCESS}cmake-config file and adjust compilers and other settings as needed.
enter the command ../cmake-config and cmake should configure everything for the build.
make && make install
If everything works, your applications should be in ${ACCESS}/bin
```

**Comment by 3rav** [comment]
Hi,

I try compiled exodus (only) in msys2 (mingw64), but I have error (see attachments).

[CMakeError.log](https://github.com/gsjaardema/seacas/files/1901874/CMakeError.log)
[CMakeOutput.log](https://github.com/gsjaardema/seacas/files/1901875/CMakeOutput.log)

I modified cmake-exodus:

```
rm -f CMakeCache.txt

cmake -G "MSYS Makefiles" \
-D SEACASProj_ENABLE_SEACASExodus=ON \
```

**Comment by gsjaardema** [comment]
Some of the errors in CMakeError.log and CMakeOutput.log are to be expected since they are the output of the CMake process trying to determine the capabilities and shortcomings of the compiler.

There should be some text output to the terminal when running the CMake process that shows the overall configuration results.  Do you have that output?

**Comment by 3rav** [comment]
Hi,

msys2 bash output:

```
Getting information for all enabled TPLs ...

Processing enabled TPL: Netcdf (enabled explicitly, disable with -DTPL_ENABLE_Ne                      tcdf=OFF)
-- Using FIND_PACKAGE(Netcdf ...) ...
CMake Error at cmake/tribits/common_tpls/find_modules/FindNetCDF.cmake:163 (mess                      age):
  Can not locate NetCDF include directory
Call Stack (most recent call first):
  cmake/tribits/common_tpls/FindTPLNetcdf.cmake:66 (find_package)
  cmake/tribits/core/package_arch/TribitsProcessEnabledTpl.cmake:106 (INCLUDE)
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1704 (TRIBITS_PROCES                      S_ENABLED_TPL)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:202 (TRIBITS_PROCESS_                      ENABLED_TPLS)
  cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:40 (TRIBITS_PROJECT)


CMake Error at cmake/tribits/common_tpls/find_modules/FindNetCDF.cmake:274 (mess                      age):
  Can not locate NetCDF C library
Call Stack (most recent call first):
  cmake/tribits/common_tpls/FindTPLNetcdf.cmake:66 (find_package)
  cmake/tribits/core/package_arch/TribitsProcessEnabledTpl.cmake:106 (INCLUDE)
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1704 (TRIBITS_PROCES                      S_ENABLED_TPL)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:202 (TRIBITS_PROCESS_                      ENABLED_TPLS)
  cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:40 (TRIBITS_PROJECT)


--      NetCDF_ROOT is C:/msys64/usr/local/seacas-master
-- NetCDF does not require HDF5
-- NetCDF does not require PNetCDF
-- Can not locate NetCDF bin directory
-- Could NOT find NetCDF (missing: NetCDF_LIBRARIES NetCDF_INCLUDE_DIRS)
-- NetCDF Version:
--      NetCDF_NEEDS_HDF5        =
--      NetCDF_NEEDS_PNetCDF     =
--      NetCDF_PARALLEL          =
--      NetCDF_INCLUDE_DIRS      = NetCDF_INCLUDE_DIR-NOTFOUND
--      NetCDF_LIBRARIES         = NetCDF_C_LIBRARY-NOTFOUND
--      NetCDF_BINARIES          = ncdump;ncgen;nccopy
-- Netcdf_LIBRARY_NAMES='netcdf'
-- Searching for libs in Netcdf_LIBRARY_DIRS=''
-- Searching for a lib in the set "netcdf":
--   Searching for lib 'netcdf' ...
--     Found lib 'C:/msys64/mingw64/lib/libnetcdf.dll.a'
-- TPL_Netcdf_LIBRARIES='C:/msys64/mingw64/lib/libnetcdf.dll.a'
-- Searching for headers in Netcdf_INCLUDE_DIRS=''
-- Searching for a header file in the set "netcdf.h":
--   Searching for header 'netcdf.h' ...
--     Found header 'C:/msys64/mingw64/include/netcdf.h'
-- Found TPL 'Netcdf' include dirs 'C:/msys64/mingw64/include'
-- TPL_Netcdf_INCLUDE_DIRS='C:/msys64/mingw64/include'
Processing enabled TPL: DLlib (enabled explicitly, disable with -DTPL_ENABLE_DLl                      ib=OFF)
-- Attempting to tentatively enable TPL 'DLlib' ...
-- DLlib_LIBRARY_NAMES='dl'
-- Searching for libs in DLlib_LIBRARY_DIRS=''
-- Searching for a lib in the set "dl":
--   Searching for lib 'dl' ...
-- NOTE: Did not find a lib in the lib set "dl" for the TPL 'DLlib'!
-- ERROR: Could not find the libraries for the TPL 'DLlib'!
-- TIP: If the TPL 'DLlib' is on your system then you can set:
     -DDLlib_LIBRARY_DIRS='<dir0>;<dir1>;...'
   to point to the directories where these libraries may be found.
   Or, just set:
     -DTPL_DLlib_LIBRARIES='<path-to-libs0>;<path-to-libs1>;...'
   to point to the full paths for the libraries which will
   bypass any search for libraries and these libraries will be used without
   question in the build.  (But this will result in a build-time error
   if not all of the necessary symbols are found.)
-- ERROR: Failed finding all of the parts of TPL 'DLlib' (see above), Aborting!

-- TPL_DLlib_LIBRARIES=''
-- Attempt to tentatively enable TPL 'DLlib' failed!  Setting TPL_ENABLE_DLlib=O                      FF

Setting up testing support ...


Configuring individual enabled SEACASProj packages ...


No ETI support requested by packages.


***
*** WARNING:  There were no packages configured so no libraries or tests/example                      s will be built!
***


Set up for creating a distribution ...


Finished configuring SEACASProj!

-- Configuring incomplete, errors occurred!
See also "C:/msys64/usr/local/seacas-master/packages/CMakeFiles/CMakeOutput.log"                      .
See also "C:/msys64/usr/local/seacas-master/packages/CMakeFiles/CMakeError.log".
```

Regards
Rafal

**Comment by gdsjaar** [comment]
Sorry it is such a pain to build.  I haven’t built on a windows system for several years and never using the CMake build system.  I’m not sure how to fix the issues you are seeing.  Perhaps remove the search for DlLib using “-DTPL_ENABLE_DLlib=OFF” in the cmake-exodus script…

..Greg

**Comment by 3rav** [comment]
Hi,

The flag “-DTPL_ENABLE_DLlib=OFF”  did not help.

The older version of the exodus compiled correctly with using the Makefile.standalone file.
[Makefile.zip](https://github.com/gsjaardema/seacas/files/1916399/Makefile.zip)

Regards
Rafal

**Comment by gsjaardema** [comment]
OK, that is good I guess -- it gives you an exodus library to use.

You might be able to modify that Makefile to work with current source if you need the current versino of the library for any reason...

**Comment by gsjaardema** [comment]
I put a Makefile.standalone into the current github exodus repository (packages/seacas/libraries/exodus/Makefile.standalone) which might build the current exodus src.  I haven't tested it much, but it seems to work if you need it...

**Comment by 3rav** [comment]
Hi,

Now (used Makefile.standalone) I have error:

```
$ make -f Makefile.standalone
echo "making exodus in src"
making exodus in src
(cd src &&  make  -f Makefile.standalone "AR=ar -rv" "CC=gcc" "CFLAGS=-O2 -O2 -Wall -DVERBOSE -I../include  -I/Users/gdsjaar/src/SEACAS/include " "RANLIB=ranlib" libexodus.a)
make[1]: Wejście do katalogu '/usr/local/seacas-master/packages/seacas/libraries/exodus/src'
gcc -c -O2 -O2 -Wall -DVERBOSE -I../include  -I/Users/gdsjaar/src/SEACAS/include  ex_add_attr.c
In file included from ex_add_attr.c:35:0:
../include/exodusII.h:45:27: fatal error: exodus_config.h: No such file or directory
compilation terminated.
make[1]: *** [Makefile.standalone:207: ex_add_attr.o] Błąd 1
make[1]: Opuszczenie katalogu '/usr/local/seacas-master/packages/seacas/libraries/exodus/src'
make: *** [Makefile.standalone:141: libexodus.a] Błąd 2
```

but after modification: exodusII.h and exodusII_int.h 
#include "exodus_config.h" to //#include "exodus_config.h", compilation with msys2 works:
```
a - ex_put_variable_name.o
a - ex_put_variable_names.o
a - ex_put_variable_param.o
a - ex_threadsafe.o
a - ex_update.o
a - ex_utils.o
D:\msys64\mingw64\bin\ar.exe: creating libexodus.a
ranlib libexodus.a
cp libexodus.a ..
make[1]: Opuszczenie katalogu '/usr/local/seacas-master/packages/seacas/libraries/exodus/src'
cp src/libexodus.a .
ranlib libexodus.a
```

**Comment by gdsjaar** [comment]
The Makefile.standalone that I created did not build the deprecated functions which are the “undefined reference” listed below.  I will update the Makefile.standalone to optionally include the deprecated functions which should get you working…

..Greg

**Comment by gsjaardema** [comment]
Try pulling again and rebuilding.  May have to do "make -f Makefile.standalone clean" first.

**Comment by 3rav** [comment]
Hi,

Now works, thank you for your help.

**Comment by gsjaardema** [comment]
Thanks for the pointer to packaging.  I will take a look, but doubt that I will have time for awhile.

Thanks for sticking with the build; sorry it was so difficult.

**Comment by 3rav** [comment]
Hi

I made file: PKGBUILD for mingw64, I include the created package.

[PKGBUILD&package.zip](https://github.com/gsjaardema/seacas/files/1937456/PKGBUILD.package.zip)
