### ISSUE TITLE
Please remove calls to deprecated Kokkos::View methods

### ISSUE THREAD

**Issue by mhoemmen** [gsjaardema/seacas#106]
Kokkos will soon deprecate the following `Kokkos::View` methods:
  1. `ptr_on_device()`: replace with `data()`
  2. `dimension(N)` (for N = 0, 1, 2, ..., 7): replace with `extent(N)`
  3. `dimension_N()` (for N = 0, 1, 2, ..., 7): replace with `extent(N)`
  4. `is_contiguous()`: replace with `span_is_contiguous()`
  5. `capacity()`: replace with `span()`

Sierra is already seeing build errors with its Trilinos integration build, since Sierra doesn't define `KOKKOS_ENABLE_DEPRECATED_CODE`.  If that macro is not defined, code that uses the above methods will not build.

Thanks!

@micahahoward @prwolfe @rrdrake

**Comment by gsjaardema** [comment]
The only use I see is `ptr_on_device()` which I have replaced on the SEACAS github.  Will hopefully push to Sierra and Trilinos "soon".

**Comment by mhoemmen** [comment]
Sierra can get around this by defining the macro, but it might actually be better to let the macro stay undefined, so we're all motivated to fix this :-)

**Comment by gsjaardema** [comment]
This should now be fixed everywhere.
