### ISSUE TITLE
Work-around for XL 16.1 compiler bug

### ISSUE THREAD

**Issue by mhoemmen** [gsjaardema/seacas#108]
See https://github.com/trilinos/Trilinos/issues/2789

**Comment by gsjaardema** [comment]
@mhoemmen  If you provide me with the patch, I will apply both here and in Trilinos.  I see no patches in https://github.com/trilinos/Trilinos/issues/2789

**Comment by gsjaardema** [comment]
See https://github.com/trilinos/Trilinos/pull/2924
