### ISSUE TITLE
nem_spread questions

### ISSUE THREAD

**Issue by nschloe** [gsjaardema/seacas#11]
It appears that `nem_spread` is configurable through a text file, but not through command line. This always creates a hassle for me since I use `nem_spread` from a script, and in there I have to open a file, write to it, call nem_spread, and delete the file.

It'd be a lot more convenient if it was fully configurable through command line.

(Besides, how do I tune it to spit out out files like `test.e.2.0`, not `test.par.2.0`?)

**Comment by gsjaardema** [comment]
The decomp script is an example of nem_slice/nem_spread use.  It creates
test.e.2.0 if the base file is test.e, so you can look at it to get an
example of how to do that.

..Greg

**Comment by nschloe** [comment]
Ah, no, I had just been looking at [this folder](https://github.com/gdsjaar/seacas/tree/master/TPL), assuming that this is where the bundling happens. Apparently it doesn't, except for Zoltan.
