### ISSUE TITLE
exodus build -> missing runcmake.sh in netcdf

### ISSUE THREAD

**Issue by albeanth** [gsjaardema/seacas#110]
Hi Greg - in the [exodus specific source](https://github.com/gsjaardema/seacas/archive/exodus.zip), the file `seacas-exodus/TPL/netcdf/runcmake.sh` seems to be missing. I was able to snag it from the main seacas source and finish off building netcdf. 

On a separate note, or at least I think separate, I am having troubles getting the following simple test to run on MacOS.
```
#include "exodusII.h"
// #include <stdio.h>

int main() {

  int CPU_word_size, IO_word_size, exoid;
  CPU_word_size = sizeof(float); /* use float or double*/
  IO_word_size = 8; /* store variables as doubles */
  /* create EXODUS II file */
  exoid = ex_create ("test.exo", /* filename path */
    EX_CLOBBER, /* create mode */
    &CPU_word_size, /* CPU float word size in bytes */
    &IO_word_size); /* I/O float word size in bytes */

  return 0;
}
```
It compiles without any errors/warnings with:
` gcc ExodusTest.c -lexodus -lnetcdf -L /path/to/seacas-exodus/lib/ -I /path/to/seacas-exodus/include/`

But when I run the executable `./a.out`, I get a library issue that causes problems.
```
dyld: Library not loaded: @rpath/libexodus.2.dylib
  Referenced from: /path/to/./a.out
  Reason: image not found
Abort trap: 6
```

Any ideas on how to fix this? Thanks in advance.

**Comment by gsjaardema** [comment]
You're welcome.  I am in process of updating the exodus branch with current files and will include the NetCDF `runcmake.sh`

**Comment by gsjaardema** [comment]
Updated exodus branch to latest version and updated the build files to match those in the mainline seacas distribution.
