### ISSUE TITLE
Converting from Exodus to CGNS?

### ISSUE THREAD

**Issue by rouson** [gsjaardema/seacas#111]
Does seacas provide a capability for the above file conversion?  If not, is there a converter you could recommend?   

I don't know enough about either format to know if such a conversion can be accomplished automatically or if there are aspects of one that cannot be translated to the other without additional information.  For present purposes, I'm interested in converting geometry only.  Boundary and initial conditions need not be included.

**Comment by gsjaardema** [comment]
It isn't really an officially supported capability, but it is something that I use for testing and seems to work very robustly in serial; still a few issues in parallel.  The capability is provided in the `io_shell` executable which basically just takes an input mesh and copies it to an output mesh.  However, it is able to do format conversions through the IOSS library.  So a basic conversion of an Exodus file to a CGNS file would be:
```
io_shell input.e output.cgns
```
If the input and output file types are not specified, then it uses a convention to guess the file type based on the extensions of the files.  An exodus type is inferred for the extensions `e`, `g`, `gen`, or `exo` and CGNS is inferred from `cgns`

There are other options to io_shell which can be seen by entering `io_shell --help`

**Comment by gsjaardema** [comment]
A little more background.  I use `io_shell` to verify that the underlying database implementations are working correctly.  For example, I will do roundtrip conversions:
```
io_shell test_file.e test_file.cgns
io_shell test_file.cgns test_file-copy.e
exodiff -pedantic test_file.e test_file-copy.e
```
To make sure that I can roundtrip the files with no loss of information.  This is also done with CGNS->Exodus->CGNS.  The io_shell executable is also gaining some options that are making is useful for some of our users to modify the contents of a file...

**Comment by rouson** [comment]
Thanks!  I'll close for now and let several colleagues know about this capability.  We'll reopen it if we encounter any problems.

**Comment by alanw0** [comment]
I haven't heard from Greg S, I hope he's sipping an umbrella drink somewhere nice. :-)
Maybe @tokusanya knows the answer.
I don't believe we've tried to read a CGNS file into a stk-mesh, but it sounds conceptually feasible given the idea of IOSS, which is to abstract specific formats. But I would guess we're lacking a little plumbing in stk-io, in terms of creating the correct IOFactory object etc.

**Comment by alanw0** [comment]
Yes it might be worth a try to use io_shell with in_type cgns and out_type exodus. I don't know if that is intended to work, but it doesn't seem outrageous.

**Comment by spdomino** [comment]
I am having issues with activating the CGNS TPL to the Trilinos/Secas build:

```
Supported database types:
	catalyst_cgns, catalyst_exodus, dof, dof_exodus, exodus, exodusII, exodusii, gen_struc, generated, genesis, heartbeat, null, textmesh
```

I added: `-DTrilinos_ENABLE_CGNS:BOOL=ON \` and see the following CGNS snippets in the log file:

`-- Setting SEACASIoss_ENABLE_CGNS=ON since Trilinos_ENABLE_SEACASIoss=ON AND Trilinos_ENABLE_CGNS=ON`

` Found CGNS: /my/path/to//gitHubWork/scratch_build/install/clang_17.0/cgns/4.1.5/lib/libcgns.a`

The only strange thing that I saw was an error proceeding the Found CGNS message above:

```
Processing enabled external package/TPL: CGNS (enabled explicitly, disable with -DTPL_ENABLE_CGNS=OFF)
-- Using find_package(CGNS ...) ...
CMake Error at cmake/tribits/common_tpls/find_modules/FindCGNS.cmake:220 (message):
  CGNS Scoping *Not* Enabled as Required.  Rebuild CGNS library with
  CGNS_ENABLE_SCOPING defined.
```

I suppose I will try a new CGNS build, however, if anyone has a CGNS and Trilinos config file that works, let me know.

**Comment by tcfisher** [comment]
@spdomino I build via spack. It looks like that uses:
```
cmake -DCGNS_ENABLE_FORTRAN:BOOL=ON -DCGNS_ENABLE_SCOPING:BOOL=ON -DCGNS_ENABLE_PARALLEL:BOOL=ON -DCGNS_ENABLE_TESTS:BOOL=OFF -DCGNS_BUILD_TESTING:BOOL=OFF -DCGNS_BUILD_CGNSTOOLS:BOOL=OFF -DCGNS_BUILD_SHARED:BOOL=OFF -DCGNS_BUILD_STATIC:BOOL=ON -DCGNS_ENABLE_BASE_SCOPE:BOOL=OFF -DCGNS_ENABLE_LEGACY:BOOL=OFF -DCGNS_ENABLE_MEM_DEBUG:BOOL=OFF -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON -DCGNS_ENABLE_64BIT:BOOL=ON -DCGNS_ENABLE_HDF5:BOOL=ON -DHDF5_NEED_ZLIB:BOOL=ON -DHDF5_INCLUDE_DIR:PATH=/path/to/hdf5/include -DHDF5_LIBRARY_DIR:PATH=/path/to/hdf5/lib -DHDF5_NEED_MPI:BOOL=ON -DHDF5_ENABLE_PARALLEL:BOOL=ON /path/to/cgns/src
```
`io_info --config` shows:
```
        CGNS Library Version: 4.3
                Default integer size is 64-bit.
                Scoped Enums enabled
                Compact Storage enabled
                Parallel enabled
                HDF5 enabled (1.10.9)
                Using HDF5 Collective Metadata.
                HDF5 Multi-Dataset NOT Available.
```
Hope that helps.

**Comment by spdomino** [comment]
Thanks, @tcfisher . I see some int64_t complexity, however, will try linux.
