### ISSUE TITLE
issue with ex_get_name() and side/node sets

### ISSUE THREAD

**Issue by albeanth** [gsjaardema/seacas#112]
Hi @gdsjaar , I'm trying to use the c function `ex_get_name()` to get the name of side sets and node sets for a given exodus file. I am able to get the set ids using `ex_get_ids()`, the number of sides/nodes in each set using `ex_get_set_param()`, and finally the elems/nodes using `ex_get_set()`. However, when I invoke `ex_get_name()` to get the name of each side/node set, I get the following error.

```
Assertion failed: (value != NULL), function getNCvx_schar_schar, file /path/to/seacas-exodus/TPL/netcdf/netcdf-4.6.1/libsrc/putget.c, line 6403.
Abort trap: 6
```

I have run `ncdump` using netcdf and in the output there are names for both the side and node sets (so I know they exist). Those are as follows:
```
 ns_names =
  "bottom",
  "right",
  "left",
  "top" ;

 ss_names =
  "right",
  "left",
  "bottom",
  "top" ;
```

Any ideas on how I can remedy that error? 

Thanks in advance.

**Comment by albeanth** [comment]
@gsjaardema that was the issue. I wasn't allocating memory for the char array... Another easy fix! Thanks again for your help.

**Comment by gsjaardema** [comment]
You’re welcome.  Glad I could help.
