### ISSUE TITLE
Blot repeats variable names on newer compiler

### ISSUE THREAD

**Issue by wortiz** [gsjaardema/seacas#117]
This appears to be related to using a newer gcc. On gcc 8 blot repeats both the first global and nodal variable names:

     Variables Names:
        Global:   CONV                              CONV                            
                  CONV                              CONV                            
                  CONV                            
        Nodal:    VX                                VX                              
                  VX                                VX                              
                  VX                                VX                              
                  VX                 

Compiling with gcc 5 instead blot correctly displays the variable names.

Grope/explore and algebra do not exhibit this issue and display variable names on gcc 8.

It seems to only be a display issue as I can paint/vec/cont other variable names, just can't see what they are in blot.

**Comment by gsjaardema** [comment]
Thanks.  Looks like an optimization problem -- works in debug, fails optimized.  Will try to see what is happening...

**Comment by gsjaardema** [comment]
Let me know if it still doesn't work for you.  Never found a root cause; just moved code around until it worked...

**Comment by wortiz** [comment]
Thanks it appears to work.

I had to change one format back as the three column rendering didn't seem to play well with terminal widths of less than around 110

    diff --git a/packages/seacas/applications/blot/prname.f b/packages/seacas/applications/blot/prname.f
    index 2d01a6f24..84686bdb1 100644
    --- a/packages/seacas/applications/blot/prname.f
    +++ b/packages/seacas/applications/blot/prname.f
    @@ -87,7 +87,7 @@ C ... Print them out.
           RETURN
     
      20   FORMAT('A',I4)
    - 30   FORMAT ('(4X, A, :, 3 (2X, ',A,'), :, /,(12X, 3 (2X, ',A,')))')
    + 30   FORMAT ('(4X, A, :, 2 (2X, ',A,'), :, /,(12X, 2 (2X, ',A,')))')
     
     10000  FORMAT (/, 1X, 'VARIABLES NAMES')
     10010  FORMAT (/, 1X, 'Variables Names:')

**Comment by gsjaardema** [comment]
OK, I will change back to 2 column.  Should have tried it with longer names...
