### ISSUE TITLE
separate docs subdirectory

### ISSUE THREAD

**Issue by ibaned** [gsjaardema/seacas#125]
It would greatly speed up clone times of this repository if the docs subdirectory were moved into a separate Git repository, and its history removed from this one.

**Comment by gsjaardema** [comment]
I will do this, but need to figure out which git method to use for the subpackage...  SEACAS is used in a few other places and they each use a different subpackage method, so I need to see how best to do this and not break their uses...

**Comment by ibaned** [comment]
Good to hear! Yes, this can be a tricky decision. I've seen several drawbacks to using git submodules (one of the possible methods). In my opinion the lowest risk is to not associate them at all using git, simply have sufficient advertisement (README, etc) that users know where to find the docs repository without git's help.

**Comment by gsjaardema** [comment]
This has been done.  Docs are now in `seacas-docs` repository.
