### ISSUE TITLE
decomp

### ISSUE THREAD

**Issue by sahirbutt** [gsjaardema/seacas#129]
I am trying to decompose an exodus mesh file using decomp, but I am getting the following error:

Executing:
/data/opt/trilinos-12.0.1/bin/nem_slice -e -S -l inertial -c -o specimem.g.nem -m mesh=200 specimen.g
...see specimen.g.decomp.out for nem_slice status

Beginning nem_slice execution.
Input Mesh File = 'specimen.g'
Using 32-bit integer mode for decomposition...
nem_slice: /data/sw/trilinos-12.0.1-Source/packages/seacas/applications/nem_slice/elb_exo_util.C:490: int read_mesh(const string&, Problem_Description*, Mesh_Description<INT>*, Weight_Description<INT>*) [with INT = int; std::__cxx11::string = std::__cxx11::basic_string<char>]: Assertion `node >= 0' failed.
/data/opt/trilinos-12.0.1/bin/decomp:  line 155: 26697 Aborted ( $LAUNCH $NEM_SLICE -e $spheres $decomp_method $nem_slice_flag -o $nemesis -m mesh=$processors $genesis >> $output )

ERROR:******************************************************************
ERROR:
ERROR During nem_slice execution. Check error output above and rerun
ERROR:
ERROR:******************************************************************

Is there an upper limit on number of nodes/elements in the mesh file when using decomp?

**Comment by gsjaardema** [comment]
If the input mesh has more than 2.1 Billion nodes or elements, then you probably need to use the `-64` command line option.  Also, with that large of a mesh, the only decomposition method that is supported is `-linear`.

Also, since the `nem_spread` and `nem_slice` which are used in the `decomp` script are serial applications, you will need a machine with lots of memory to decompose a billion-element mesh.

If your mesh is that large, I can propose other options for decomposition; if the mesh is smaller than that, there is probably some other issue causing the problem.

**Comment by sahirbutt** [comment]
The mesh files I tried to decompose had 66, 72 and 88 Million nodes. I was able to mesh the one with 66M nodes, but the other two give the same error (Assertion `node >= 0' failed). I tried -linear flag also, but the error persists. 
The mesh file which I have to finally decompose has less than 500 M nodes and I am running this on a machine with around 200 GB RAM.
What can cause this error? What other option do I have to decompose it? Thanks!

**Comment by gsjaardema** [comment]
Not sure what would cause the issue on a mesh of that size.  The `node` that it is referring to is an entry in the element block connectivity.   You might try doing `explore {mesh.g}` followed by `check` at the prompt to see if `explore` can find any issues with the mesh.

How is the mesh being generated and how many element blocks are there and what types of elements?

**Comment by sahirbutt** [comment]
The mesh is generated using trelis, there is only 1 element block, 2 NodeSets and all elements are hexahedrons.
And explore/grope with check shows problems with the mesh file (with connectivity, as you said)...

` *** ELEMENT CONNECTIVITY ERROR: Found 4891264 errors in element connectivity check for element block 1
 *** Local Node 72763506 (Global Node 73605589) is not connected to any elements
 *** Local Node 72763507 (Global Node 73605590) is not connected to any elements
 *** Local Node 72763508 (Global Node 73605591) is not connected to any elements
 *** Local Node 72763509 (Global Node 6420404) is not connected to any elements
 *** Local Node 72763510 (Global Node 73605592) is not connected to any elements
 *** Local Node 72763511 (Global Node 414194) is not connected to any elements
 *** Local Node 72763512 (Global Node 73605593) is not connected to any elements
 *** Local Node 72763513 (Global Node 73605594) is not connected to any elements
 *** Local Node 72763514 (Global Node 73605595) is not connected to any elements
 *** Local Node 72763515 (Global Node 73605596) is not connected to any elements
 *** ...skipping additional errors... (use command "maxerr #" to change)
 *** NODE USE ERROR: Found 5301508 nodes that are not connected to any elements.
*** Error in `grope': free(): invalid pointer: 0x00007fc9175bc010 ***
`
and finally ends with a segmentation fault..
So, this problem is with the mesh generator, right? Any thoughts on that or a way around? Thanks!

**Comment by gsjaardema** [comment]
It looks like a mesh generator issue.  Can you do a `ncdump -h {mesh.g}` and either attach the output or put it in the issue.  It might give me some idea on what to look for or to have the trelis developers look at.

**Comment by sahirbutt** [comment]
`ncdump -h specimen.g
netcdf specimen {
dimensions:
	len_string = 33 ;
	len_line = 81 ;
	four = 4 ;
	len_name = 33 ;
	time_step = UNLIMITED ; // (0 currently)
	num_dim = 3 ;
	num_nodes = 78065013 ;
	num_elem = 72000000 ;
	num_el_blk = 1 ;
	num_node_sets = 2 ;
	num_el_in_blk1 = 72000000 ;
	num_nod_per_el1 = 8 ;
	num_qa_rec = 1 ;
	num_nod_ns1 = 195065 ;
	num_nod_ns2 = 195065 ;
variables:
	double time_whole(time_step) ;
	int eb_status(num_el_blk) ;
	int eb_prop1(num_el_blk) ;
		eb_prop1:name = "ID" ;
	int ns_status(num_node_sets) ;
	int ns_prop1(num_node_sets) ;
		ns_prop1:name = "ID" ;
	double coordx(num_nodes) ;
	double coordy(num_nodes) ;
	double coordz(num_nodes) ;
	char eb_names(num_el_blk, len_name) ;
	char ns_names(num_node_sets, len_name) ;
	char coor_names(num_dim, len_name) ;
	int connect1(num_el_in_blk1, num_nod_per_el1) ;
		connect1:elem_type = "HEX8" ;
	char qa_records(num_qa_rec, four, len_string) ;
	int elem_map(num_elem) ;
	int elem_num_map(num_elem) ;
	int node_num_map(num_nodes) ;
	int node_ns1(num_nod_ns1) ;
	double dist_fact_ns1(num_nod_ns1) ;
	int node_ns2(num_nod_ns2) ;
	double dist_fact_ns2(num_nod_ns2) ;

// global attributes:
		:api_version = 6.05f ;
		:version = 6.05f ;
		:floating_point_word_size = 8 ;
		:file_size = 1 ;
		:maximum_name_length = 32 ;
		:int64_status = 0 ;
		:title = "cubit(1/butt/trelis/specimens/specimen.g): 12/10/2018: 11" ;
}`
Thank you for your help.

**Comment by gsjaardema** [comment]
The issue, I think, is that the NetCDF format (which is underneath exodus) has a few different formats which have different limitations.  In the `CDF2` format (which this file is using based on the `file_size=1` setting) has a limit of 2 GiByte limit per variable.  The main variables that hit the limit first are typically the `coord{xyz}` or the `connect#`.  In your case, it is the `connect1` variable which contains 72000000 elem * 8 node/element * 4 byte/node = 2,304,000,000 bytes which is larger than allowed in this format.

There are a couple things that can be done.  One is to use the `netcdf4` variant of the NetCDF format.  I'm not sure if or how this can be specified with trelis -- you will have to ask them.  The other option is to split the model such that there are two or more element blocks.

Exodus can support multi-billion element models, but the correct underlying NetCDF format needs to be used as the models get larger.  I'm not sure why there wasn't an error output when the mesh file was created; I will try to verify that the libraries are correctly detecting this issue.

**Comment by gsjaardema** [comment]
For further confirmation, I took the `ncdump` output from above and fed it to `ncgen` and got the following error:
```
s1018191:build(master)> ../bin/ncgen -o tmp.g tmp.nc
ncgen: NetCDF: One or more variable sizes violate format constraints
```
Which confirms the issue.

**Comment by sahirbutt** [comment]
I tried making two blocks in the mesh and it worked :+1:
Thank you so much for your help!!

**Comment by gsjaardema** [comment]
Good.
