### ISSUE TITLE
install-tpl.sh: undefined references when building NetCDF

### ISSUE THREAD

**Issue by daniellivingston** [gsjaardema/seacas#130]
When running the command 

    CGNS=NO MATIO=NO SHARED=NO NEEDS_ZLIB=YES GNU_PARALLEL=OFF ./install-tpl.sh

on a fresh Ubuntu 16.04 install, the following error is thrown:

```
[ 24%] Linking C executable ncgen
/home/daniel/LaGriT/seacas/lib/libhdf5.a(H5PLint.o): In function `H5PL__close':
H5PLint.c:(.text+0x4f8): undefined reference to `dlclose'
/home/daniel/LaGriT/seacas/lib/libhdf5.a(H5PLint.o): In function `H5PL__open':
H5PLint.c:(.text+0x552): undefined reference to `dlopen'
H5PLint.c:(.text+0x56d): undefined reference to `dlsym'
H5PLint.c:(.text+0x605): undefined reference to `dlerror'
/home/daniel/LaGriT/seacas/lib/libhdf5.a(H5PLplugin_cache.o): In function `H5PL__find_plugin_in_cache':
H5PLplugin_cache.c:(.text+0x32a): undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
ncgen/CMakeFiles/ncgen.dir/build.make:749: recipe for target 'ncgen/ncgen' failed
make[2]: *** [ncgen/ncgen] Error 1
CMakeFiles/Makefile2:613: recipe for target 'ncgen/CMakeFiles/ncgen.dir/all' failed
make[1]: *** [ncgen/CMakeFiles/ncgen.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```
Note that HDF5 appeared to be built successfully.

**Comment by gsjaardema** [comment]
Yes, I hit this late last week.  It is a problem in the NetCDF configuration files in that they do not correctly pick up all HDF5 dependencies.  They get the direct libhdf5.a and libhdf5_hl.a, but not the dependencies of HDF5 itself --  libdl.a (although libz.a seems to be found).  These get found correctly in an build with shared libraries, but not with static (non-shared) libs.

I've updated the `runcmake.sh` in `TPL/netcdf` to add `-ldl` as an explicit dependency if shared libs are disabled.  This runs correctly on my system; hopefully on yours also.  Should be able to just do a `git pull` to get the updated `runcmake.sh`.  If that won't work for you, I can provide a patch to apply to your already checked out source.

**Comment by daniellivingston** [comment]
I did a fresh pull and it works perfectly now.
Thank you very much!
