### ISSUE TITLE
Small problem with NetCDF

### ISSUE THREAD

**Issue by knepley** [gsjaardema/seacas#132]
I have NetCDF 4.3.2 installed. I have a compile error since configure does not check that netcdf_meta.h actually exists. Here are the small changes I made to fix this:

```
diff --git a/packages/seacas/libraries/exodus/include/exodusII.h b/packages/seacas/libraries/exodus/include/exodusII.h
index 44daf26..1928996 100644
--- a/packages/seacas/libraries/exodus/include/exodusII.h
+++ b/packages/seacas/libraries/exodus/include/exodusII.h
@@ -46,7 +46,7 @@
 
 #include "netcdf.h"
 
-#define NC_HAVE_META_H
+/* #define NC_HAVE_META_H */
 #if defined(NC_HAVE_META_H)
 #include "netcdf_meta.h"
 #if NC_HAS_PARALLEL
diff --git a/packages/seacas/libraries/exodus/src/ex_utils.c b/packages/seacas/libraries/exodus/src/ex_utils.c
index 80c0658..7ced3d3 100644
--- a/packages/seacas/libraries/exodus/src/ex_utils.c
+++ b/packages/seacas/libraries/exodus/src/ex_utils.c
@@ -101,7 +101,9 @@ void ex_print_config(void)
 #else
   fprintf(stderr, "\tExodus Deprecated Functions Available\n\n");
 #endif
+#if defined(NC_HAVE_META_H)
   fprintf(stderr, "\tNetCDF Version %s\n", NC_VERSION);
+#endif
 #if NC_HAS_HDF5
   fprintf(stderr, "\tUsing NetCDF with HDF5 enabled\n");
 #endif
```
I can make a PR if you think this is the correct fix. Thanks, Matt

**Comment by gsjaardema** [comment]
Thanks for catching that.  That line should be removed altogether.  (`#define NC_HAVE_META_H`).  It was put in when the NetCDF package had a bug recently in which they didn't define `NC_HAVE_META_H` in `netcdf.h` even though the `netcdf_meta.h` existed.

I thought I had removed that once they fixed the bug, but as you found out, I didn't.  

I will remove, but thanks for catching it.
