### ISSUE TITLE
missing byte encoding in python3 exodus.py

### ISSUE THREAD

**Issue by ecoon** [gsjaardema/seacas#145]
So amusingly enough, I came here to ask whether you would take a contribution of a python3 version of exodus.py, only to find that Greg had pushed one what, yesterday?  So thanks for the timely update :)

I tried it out and it seems to work for me except for two missed string-to-byte conversions, where "NFACED" and "NSIDED" need to be byte strings, e.g. 

https://github.com/gsjaardema/seacas/blob/master/packages/seacas/scripts/exodus-3.py.in#L3355

and

https://github.com/gsjaardema/seacas/blob/master/packages/seacas/scripts/exodus-3.py.in#L3387

should read 

`b"NFACED"`  and `b"NSIDED"`.

I also think it would be useful to not require the user to provide byte strings for things like set names, coordinate names, etc.  This would simply require making all of the `put_*_name()` functions call `encode('ascii')` on their arguments.  But that is less important than fixing these bugs.  Let me know if you would prefer a pull request.

**Comment by gsjaardema** [comment]
This should be fixed now.  I didn't do the `put_*_name()` functions as I got errors on my first attempt.  Will try to take a closer look to see what I was doing wrong.  Will also accept PR if you have one.

**Comment by gsjaardema** [comment]
I am working on the `encode` and `decode` that are needed for the names.  FYI just so no-one is duplicating effort.

**Comment by gsjaardema** [comment]
I think this should be fixed now.  Let me know if there are any other issues with the Python-3 version.

**Comment by ecoon** [comment]
It is close -- I think this introduced a new bug though?

https://github.com/gsjaardema/seacas/blame/master/packages/seacas/scripts/exodus-3.py.in#L4410

`__ex_put_names()` expects a string (i..e a key into the dictionary in `ex_obj_from_inq`) but is used with an `objID` instead.

**Comment by gsjaardema** [comment]
Thanks, good catch.  I think I have those fixed; I didn't see that you had someone working on a PR.

There is definitely some inconsistency in how the objType is passed down to the lower-level __ex* routines -- some do the `ex_inquiry` in the calling code and some down in the `__ex_*` routine.  I think it makes sense to do at the lowest level, so will try to fix that over time.  Definitely need some better testing also...

**Comment by gsjaardema** [comment]
I think this should be fixed now.  Feel free to reopen if you find any issues.
