### ISSUE TITLE
Question on locale in python3 exodus

### ISSUE THREAD

**Issue by wortiz** [gsjaardema/seacas#146]
I get an error here on my OS (ubuntu 18.04):

https://github.com/gsjaardema/seacas/blob/624b6b8c2dcafb51094543b93d424391f2a7901a/packages/seacas/scripts/exodus-3.py.in#L99

Was wondering what it is used for in the script

By default ubuntu 18.04 (or at least my version) does not have en_US, switching to en_US.UTF-8 removes error, I suppose I could also enable en_US

    $ locale -a
        C
        C.UTF-8
        en_AG
        en_AG.utf8
        en_AU.utf8
        en_BW.utf8
        en_CA.utf8
        en_DK.utf8
        en_GB.utf8
        en_HK.utf8
        en_IE.utf8
        en_IL
        en_IL.utf8
        en_IN
        en_IN.utf8
        en_NG
        en_NG.utf8
        en_NZ.utf8
        en_PH.utf8
        en_SG.utf8
        en_US.utf8
        en_ZA.utf8
        en_ZM
        en_ZM.utf8
        en_ZW.utf8
        POSIX

**Comment by gsjaardema** [comment]
Basically, it is only used in a couple of the output routines to add "language-specific" formatting of large integers.  In other words, it will output `1,234,567` instead of `1234567` in the `summarize()` function.  

I will try to see if there is a way to see if a specific locale exists before using it...

**Comment by gsjaardema** [comment]
I can probably do something like:
```
try:
            locale.setlocale(locale.LC_ALL, 'en_US')
        except locale.Error:
            locale.setlocale(locale.LC_ALL, 'C')
```

I'm not sure why I didn't use the `en_US.utf8`.  It seems like I tried it and got an error somewhere...  Will have to see if I can figure out why...

**Comment by wortiz** [comment]
Thanks for the info.

en_US.utf-8 appears to be available on redhat 6/7 and ubuntu 18.04, at least the ones I have access too

**Comment by gsjaardema** [comment]
On my mac, it is `en_US.UTF-8` and seems to be case-sensitive.  I will check some more, but for now I have added the `try/catch` so you can give that try.

**Comment by gsjaardema** [comment]
Although now it seems to work with either case...  I've changed it use the `try/catch` and `en_US.utf-8`.  See how that works for you.

**Comment by wortiz** [comment]
On my machine I used:

    locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')

and it worked, locale.gen appears to have the uppercase as well, unsure why locale -a reports utf-8 as lowercase

Both upper and lowercase UTF-8 appear to work on my machine for setlocale (ubuntu 18.04)

Your try fix worked for me thanks.
