### ISSUE TITLE
EXODUS II: incorrect handling of the first coordinate variable in file

### ISSUE THREAD

**Issue by vadim-z** [gsjaardema/seacas#147]
Hello,

I have found a problem with coordinate handling in EXODUS II.
It happens when:

1. EXODUS II file is "large" model
2. some coordinate variable (coordx, coordy, coordz) is the first variable in netCDF storage.

In a file [ex_get_coord.c](https://github.com/gsjaardema/seacas/blob/master/packages/seacas/libraries/exodus/src/ex_get_coord.c)  coordinate variables are first inquired (LL184-213) and then read if their ID != 0 (L236) . But zero variable ID is absolutely legal in netCDF ([proof](https://www.unidata.ucar.edu/software/netcdf/docs/tutorial_ncids.html))  and corresponds to the first variable.

So, if any coordinate variable happens to be the first in netCDF storage layer (id == 0) then it would not be read by the ex_get_coord function.

Here's the CDL definition of such file: https://gist.github.com/vadim-z/fe84743083d952b897e895b330e4b8cc . The Y coordinates are not read from this file by the ex_get_coord function.

If I understood it correctly, the comparison above is required when user provides NULLs for some output coordinate arrays. Maybe it's better to use -1 as the placeholder of coordinate variable ID.

I think user shouldn't bump into this issue when he uses EXODUS library to write files, because "time_whole" variable is always written first. However I have made my own tool to create EXODUS II files and the order of netCDF variables in created files is quite random. Sometimes "bad" files are created which cannot be correctly read by EXODUS II library and consequently by VTK and ParaView tools. (Example is given above).

Interestingly, VisIt rolls its own EXODUS reader and has no problems reading such files.

PS: by grepping "coordid != 0" I've found other functions (ex_get/put_partial_coord, ex_get/put_coord) which use this pattern.

**Comment by gsjaardema** [comment]
Thanks for the detailed description.  This should now be fixed as of 4bb87f6495bd0e120839c9ac75b895c8ab06264c.  Exodus version is now 7.24
