### ISSUE TITLE
Blot fails to open file if it is working directory path has a space in it

### ISSUE THREAD

**Issue by wortiz** [gsjaardema/seacas#153]
This isn't a big deal but I thought I'd report in case it is an easy fix.

Blot fails to open a file if somewhere in the working directory path for a file there is a space in it

Both algebra and explore appear to work fine

    $ pwd
    /home/wortiz/test space/tmp

Trying to open box.e in this directory

    blot box.e

Blot fails with

     FATAL ERROR - Database "space/tmp/box.e" does not exist.

**Comment by gsjaardema** [comment]
Thanks.  If you need this to work soon, you should be able to take the `abspath ${FOR011}` out of the blot script.  This doesn't break anything; It was added to give some better QA information (full path vs local path) but not really needed...
