### ISSUE TITLE
reading file with exomerge.py

### ISSUE THREAD

**Issue by kayarre** [gsjaardema/seacas#157]
I created a mesh using pygmsh, and exported to exodus with meshio.

when I try to read it with exomerge I get the following error.

```
        Warning: failed to locate number of info records in file id 65536
        NetCDF: Invalid dimension ID or name
```
here is the mesh.
[rectangle2.zip](https://github.com/gsjaardema/seacas/files/3906272/rectangle2.zip)

**Comment by gsjaardema** [comment]
This should be fixed now in exomerge-8.5.1
