### ISSUE TITLE
exodus.py assert error

### ISSUE THREAD

**Issue by kayarre** [gsjaardema/seacas#158]
Should node sets and side sets should be optional?

https://github.com/gsjaardema/seacas/blob/8541f70dff3371ed39450022673bfd1af6c110fd/packages/seacas/scripts/exodus3.in.py#L585-L587

**Comment by gsjaardema** [comment]
Yes, if numNodeSets or numSideSets is `None`, then they shoudl just be set to 0 and the code should proceed.

**Comment by gsjaardema** [comment]
This has been fixed in exodus.py - 1.19.2 (python3 version) and 1.15 (python2 version)
