### ISSUE TITLE
Fastest way to read only num_nodes from Exodus file?

### ISSUE THREAD

**Issue by jwpeterson** [gsjaardema/seacas#163]
Hi,

Apologies if this is not the right place to post questions. I would like to know what the recommended/fastest way to read just the header information from an Exodus file using the C API is?  One obvious approach (which we implemented [here](https://github.com/libMesh/libmesh/pull/2492)) is to call
```
ex_open(filename, EX_READ,...);
ex_get_init_ext(...);
ex_close(...);
```
but I found that this approach seems to take time proportional to the file size rather than proportional to the amount of data actually read. In some cases, I found that just reading the header was only about 25% faster than reading and parsing the entire file (including nodes, elements, sidesets, etc.). 

Does this result seem reasonable based on what you know about the internals of ex_open? For example, is ex_open responsible for reading the entire file into memory so that all subsequent reads are relatively fast? This would explain the behavior that I observed. If there is a faster way of extracting a relatively small amount of information from an Exodus file, perhaps using lower level NetCDF calls, etc., I would appreciate any hints you can provide.

Thanks,
John

**Comment by gsjaardema** [comment]
There are some issues with the NetCDF library needing to read all dims and vars when it first opens the file which can take some time for large models.  More recent versions of the library have  made this more efficient, so if you are using an older library, that may be the cause of some slowdown.  For parallel, this was even worse, but we have fixed a lot of the inefficiencies.

There should not be any bulk-data input during the ex_open call, so there should be no difference in opening a file with 10,000,000 nodes/elements versus one with 100,000 nodes/elements as long as the structure is similar (blocks, variable counts, ...)   I will try to do some experiments to see if that is the case.

If you need all the metadata, ex_get_init_ext would probably be the best.  If just need a few variables, can query via ex_inquire_int() to get just what you want.

**Comment by jwpeterson** [comment]
> There should not be any bulk-data input during the ex_open call, so there should be no difference in opening a file with 10,000,000 nodes/elements versus one with 100,000 nodes/elements

OK, thanks for this info. We did recently update to NetCDF 4.6.2, but we are unfortunately on a much older version of Exodus (5.22) so possibly getting up to date there would help with this issue. 

> If you need all the metadata, ex_get_init_ext would probably be the best. If just need a few variables, can query via ex_inquire_int()

That's a good suggestion. We really only need `num_nodes` or `num_elem` so that we can have a rough estimate of the size of the mesh stored in the file. We considered just looking at the file size, but that can vary (for example if there are a lot of material properties/elemental variables) independently of the mesh size and may not be the best proxy for us.
