### ISSUE TITLE
exodus.py copy broken

### ISSUE THREAD

**Issue by wortiz** [gsjaardema/seacas#172]
commit 1e3ec2a9 breaks old script using ex_copy

I have some initialize scripts to initialize some field variables on an exodus mesh, I was using `exodus.copy` to make a copy of the input mesh and then add variables to that copy. Before that commit I was getting an error but it would still initialize the mesh so I had ignored it. Now it errors out due to file being open.

Previously it used to give this error on the ex_close of the copy:

`Exodus Library Warning/Error: [ex__check_valid_file_id]
	ERROR: In "ex_close", the file id 65536 was not obtained via a call to "ex_open" or "ex_create".
		It does not refer to a valid open exodus file.
		Aborting to avoid file corruption or data loss or other potential problems.`

Now `ERROR: The file 'initial.exoII' is open for both read and write. File corruption or incorrect behavior can occur.` occurs

Here is an example if needed: [example_bug.tar.gz](https://github.com/gsjaardema/seacas/files/4623370/example_bug.tar.gz) can be run with `python3 initialize.py domain.g initial.exoII`

Maybe I'm using the copy function incorrectly, is there something else I should be doing instead of copy here?

**Comment by wortiz** [comment]
Sorry wrong commit b47f7a0 edited in comment

**Comment by wortiz** [comment]
Again wrong, sorry I keep copying the parent commit 1e3ec2a9

**Comment by gsjaardema** [comment]
Should be fixed now.  The exodus.py copy routine was closing the input file and not the output copied to file which explains why you would get both errors/warnings -- the file was opened twice and the input file had already been closed...

**Comment by wortiz** [comment]
Works for me, thanks for the quick fix.

**Comment by gsjaardema** [comment]
Thanks for catching that.  It is the second bug so far that the multiple-open fix has exposed.
