### ISSUE TITLE
A couple gcc-10 issues

### ISSUE THREAD

**Issue by wortiz** [gsjaardema/seacas#175]
Here are a couple of issues I found with gcc-10

blot_x11 segfaults now, valgrind gives a number of invalid writes but I haven't debugged it very far. This happens with older seacas versions (before your fixes for gfortran-10, compiled with flags to make the new requirements into warnings)

the new -fno-common (https://gcc.gnu.org/gcc-10/porting_to.html ) hits 3 files, for some reason doesn't show up on toolchain ppa for 18.04 gcc-10

The varray, rarray, garray, barray are declared in 3 files

cgi/pst_pstxlate.c
cgi/x11_x11xlate.c
cgi/met_metxlate.c

Kind of looks like those could be declared static for each file or moved to locals as they don't appear to be large in size or used as globals

Also noticed in cmake-config (https://github.com/gsjaardema/seacas/blob/master/cmake-config#L386 ) CMAKE_FORTRAN_FLAGS should be CMAKE_Fortran_FLAGS otherwise flags don't actually get used

**Comment by gsjaardema** [comment]
Thanks.  It is good to know that the segfault happens for you and also before my changes.  I was trying to track that down (I should have mentioned it somewhere that gcc-10 builds, but doesn't all run).  

I was testing on my Mac system and valgrind doesn't run there, so if you could post the traceback that valgrind is giving you, it might help me track the problem down more.

I will see what I can do about the rarray, varray, garray, and barray.

Will fix the FORTRAN_FLAGS.  Thanks.

**Comment by wortiz** [comment]
Here are asan and valgrind

[asan.txt](https://github.com/gsjaardema/seacas/files/4685339/asan.txt)
[valgrind.txt](https://github.com/gsjaardema/seacas/files/4685340/valgrind.txt)

**Comment by gsjaardema** [comment]
I have fixed the rarray, varray, garray, and barray -- made them static as you suggested.  I'm not sure they are even used and will dig deeper at some point.

Also fixed the 'CMAKE_Fortran_FLAGS` as you noted.

**Comment by gsjaardema** [comment]
I've looked deeper into the blot core dump (actually a problem with the SUPES memory manager).  For some reason, it looks like there is a 16-byte offset happening somewhere.  The address that supes provides is 16 bytes prior to the beginning of the memory space that was allocated.  

I have not yet been able to determine why/how/where that is happening.  Re-familiarizing myself with the code to see what could potentially be affecting this...  Very strange.

**Comment by gsjaardema** [comment]
I think these issues should now be fixed.  The supes memory manager issue was fixed by a 'SAVE MYV' statement.  There was already a 'SAVE' statement in that routine which should have applied to everything, so not sure why it needed the extra save...   

Also fixed some other bugs found by the sanitizer.

**Comment by wortiz** [comment]
Thanks for the quick fix, valgrind doesn't turn up anything either

Maybe a change in behavior for save since MYV isn't initialized just used as a reference for memory it isn't caught by default save

It looks like the change to CMAKE_Fortran_FLAGS didn't get committed

**Comment by gsjaardema** [comment]
Strange... I remember comitting, but it definitely wasn't there.  Should be there now.
