### ISSUE TITLE
Exodus library exits on error

### ISSUE THREAD

**Issue by rms7326** [gsjaardema/seacas#182]
After successfully opening an Exodus file (ex_open return value >= 0)  using the latest 2020-05-12 library release, I make a call to ex_inquire_int() using the handle returned from ex_open() and a desired inquiry constant. The Exodus library proceeds to call ex_inquire_internal() from where it makes a call to ex__check_valid_file_id(). This function fails to validate the file for some reason (perhaps the file was not written correctly or it is corrupt) and the function sets ex_opts(EX_ABORT | EX_VERBOSE) and then calls ex_err() which calls exit() because of the ex_opts flags and my application crashes. I was expecting to find some way to prevent the exit like you can with HDF5 by calling H5dont_atexit() but it doesn't appear that the Exodus library provides a way to avoid shutting down the application. Is this true? If so I would like to submit a request to have this behavior changed. We are using Exodus in a desktop visualization system that needs to report errors to the user and remain active. In the meantime I will have to modify the library to prevent it from calling exit() :(

**Comment by rms7326** [comment]
I should mention that line 127 of seacas/libraries/exodus/src/ex_conv.c is the only place where the library forcibly sets the ex_opts flag to EX_ABORT. If it did not do that the library wouldn't have exited. Is it possible that this call to ex_opts from within the library code should not be made. It seems like this should be a client application decision as is demonstrated in many of the examples and tests.

**Comment by gsjaardema** [comment]
The reasoning for calling abort if `ex__check_valid_file_id()` fails is that it was the easiest way to add the function to the library.  I guess I should have instead had each call check the return value and then return from the function if the check failed; I will look at making that change instead of aborting.

The failure is not due to a corrupt file -- it is due to the `id` being passed is not valid and does not refer to a valid exodus file.  If it is truly the same id that was returned from `ex_open()`, then there is something wrong somewhere...  

What is the `id` value that is reported as invalid in the `ex__check_valid_file_id()` error message?

**Comment by rms7326** [comment]
Thanks for looking into this. Here is the error message right before exiting.

Exodus Library Warning/Error: [ex__check_valid_file_id]
	ERROR: In "ex_inquire_internal", the file id 65536 was not obtained via a call to "ex_open" or "ex_create".
		It does not refer to a valid open exodus file.
		Aborting to avoid file corruption or data loss or other potential problems.

And yes, this is the first ex_ library call after successfully opening the file. By successful I mean that it returned a positive number.

**Comment by gsjaardema** [comment]
That is a valid file.  After you build the SEACAS/exodus, if you do "ctest -j8", do you get all passes, or are there any failures?

If you do `exo_format sharpcone_h_0.08a.exoII` or `explore sharpcone_h_0.08a.exoII` does it work correctly?

Can you send me a copy of the program source that is giving you problems...

**Comment by rms7326** [comment]
I don't see exo_format or explore applications in the build tree. Perhaps I need to enable them in CMake for them to build. 

The results of running ctest are below. They all passed so it looks like it must be something I'm doing. I moved the call to ex_open and ex_inquire further up in my program execution and it worked so perhaps I corrupted memory somehow. You can disregard the direct issue with this file. Nevertheless, my point still stands about the library performing an exit(). It should never do that on detection of an invalid condition if it is outside of the control of the client. Perhaps this is the case here. If you are saying the only way it would perform this call to exit() is if the client passed illegal input then it is a pre-condition and you would be justified in exiting. If the client gave valid information and it is just a corrupt file it shouldn't exit.

Thanks for looking into this.

michael@tpw101:seacas/libraries/exodus>ctest -j8                            
Test project /home/michael/tecdev/3rdpartylibs/exodus/2020-05-12/_build/linux64-centos6.10/packages/seacas/libraries/exodus
    Start 1: SEACASExodus_CreateEdgeFaceWithConcats
    Start 3: SEACASExodus_exodus_unit_tests
    Start 4: SEACASExodus_exodus_unit_tests_nc4_env
    Start 5: SEACASExodus_exodus_nc4_unit_tests
    Start 6: SEACASExodus_exodus_unit_tests_nc5_env
1/6 Test #1: SEACASExodus_CreateEdgeFaceWithConcats ...   Passed    0.03 sec
    Start 2: SEACASExodus_ReadEdgeFaceWithConcats
2/6 Test #2: SEACASExodus_ReadEdgeFaceWithConcats .....   Passed    0.01 sec
3/6 Test #5: SEACASExodus_exodus_nc4_unit_tests .......   Passed    0.15 sec
4/6 Test #6: SEACASExodus_exodus_unit_tests_nc5_env ...   Passed    1.21 sec
5/6 Test #3: SEACASExodus_exodus_unit_tests ...........   Passed    1.27 sec
6/6 Test #4: SEACASExodus_exodus_unit_tests_nc4_env ...   Passed    4.15 sec

100% tests passed, 0 tests failed out of 6

Label Time Summary:
SEACAS    =   6.81 sec*proc (6 tests)

Total Test time (real) =   4.15 sec

**Comment by rms7326** [comment]
I found the piece of code that fails even in a simple program:

`int32_t appWordSize = 8;
int32_t floatingPointSize = 0;
float version = 0.0;
int32_t fileID = ex_open("/customerdata/staging/loader/Exodus/sharpcone_h_0.08a.exoII",
                         EX_READ, &appWordSize, &floatingPointSize, &version);
if (fileID >= 0)
{
    // tell the library we are expecting strings that are potentially longer than the older 32 char limit, MAX_STR_LENGTH
    int64_t maxNameLength = std::max(ex_inquire_int(fileID, EX_INQ_DB_MAX_ALLOWED_NAME_LENGTH),
                                     static_cast<int64_t>(MAX_STR_LENGTH));
    ex_set_max_name_length(fileID, maxNameLength);

    // scan the dataset title
    int32_t dummyInt32 = 0;
    float dummyFloat = 0.0;
    char* title = new char[maxNameLength+1]; // ...pre-allocate space for Exodus
    VERIFY(ex_inquire(fileID, EX_INQ_TITLE, &dummyInt32, &dummyFloat, title) == 0);

    delete[] title;
    ex_close(fileID);
}
`

**Comment by gsjaardema** [comment]
The error is in the line `ex_inquire(fileID, EX_INQ_TITLE, &dummyInt32, &dummyFloat, title)`.  The title should be of size `MAX_LINE_LENGTH+1` and not `maxNameLength+1`.  The `name` length is for entity (blocks, sets) and variable names.  The info records and the title are `MAX_LINE_LENGTH` and the QA records are `MAX_STR_LENGTH`

The program was overwriting memory which was causing the error.  If you change the length of `title`, then the program seems to run fine and there are no errors using valgrind.

**Comment by rms7326** [comment]
Thank you for that clarification. I must admit, the Exodus library isn't really clear, at least in the doxygen comments for the APIs, about what string allocations are required for the various calls.

**Comment by gsjaardema** [comment]
Thanks, I will try to improve the documentation... Never seems to be time to do it, but it would have saved us both a lot of time here if it was more clear.

Also, I have modified the `ex__check_valid_file_id()` function to not abort unless the user has `EX_ABORT` option set.  Thanks for suggesting the improved consistency with other parts of th elibrary.
