### ISSUE TITLE
Attributes

### ISSUE THREAD

**Issue by rms7326** [gsjaardema/seacas#183]
Are nodal and element block attributes essentially non-transient nodal and cell centered dataset variables? I noticed that each element block can be queried for the attribute names. Are these element block attribute names guaranteed to be the same across all blocks within an Exodus file? If so, is there a query function for getting the element block attribute names without having to dig into the first block to get them?

**Comment by gsjaardema** [comment]
Yes, attributes are essentially non-transient variables.

For element attributes, they can be different on different blocks of the model, so the only query for element attribute names is block-based; there is no way to get the "union" of all attribute names on the model.

**Comment by rms7326** [comment]
Thanks, that clarification is helpful.
