### ISSUE TITLE
Question about how exodus and cubit handle higher-order elements

### ISSUE THREAD

**Issue by rweed** [gsjaardema/seacas#192]
I'm trying to write an exodus file that has 15 node tets. The node ordering and node locations are the same used in VTK/Paraview and is basically the same quadratic element described in Betrand et al. "Tetrahedral elements for Fluid Flow", International Journal for Numerical Methods in Engineering, Vol 33, pp 1251-1267,
1992. Looking at the PATRAN manuals however, I see that the 15 node tet given there is a degenerate Hex27 and has different node locations for the face nodes (at 1/4 points instead of 1/3 points). My question is as follows. 

1. If I'm just storing and retrieving the data, the node locations and order shouldn't matter except for viz purposes in Paraview etc. However, I would like to (eventually) be able to import a 15 node tet generated by Cubit. Does Cubit support the Bertrand 15 node tet or just the degenerate PATRAN element. If Cubit only generates the PATRAN element,  I'll need to interpolate the face nodes etc to the Bertrand 15 node tet locations but I've yet to find the basis/shape functions for the degenerate PATRAN Tet15. Can someone send me the basis/shape functions for the PATRAN Tet15 element

Thanks
RW

**Comment by gsjaardema** [comment]
You will have to ask the Cubit team about their Tet15 support -- Try cubit-help@sandia.gov I think.
