### ISSUE TITLE
Update TriBITS

### ISSUE THREAD

**Issue by ibaned** [gsjaardema/seacas#194]
Hello,

There are some bug fixes in TriBITS that were added in September 2020 to fix installs on Mac, and I've encountered those bugs with the TriBITS in SEACAS. The change the I need most is TriBITSPub/TriBITS#327. I'm not familiar with how SEACAS wants to update TriBITS: all at once or just grabbing specific changes. I can help create a pull request if I know what we want that to look like.

Thank you

**Comment by gsjaardema** [comment]
I will snapshot in the current TriBITS; hopefully today.

**Comment by gsjaardema** [comment]
This should now be fixed with latest commit

**Comment by ibaned** [comment]
Yes, the Mac install issue is fixed! Thank you
