### ISSUE TITLE
Aprepro: "fatal" options do nothing

### ISSUE THREAD

**Issue by ibaned** [gsjaardema/seacas#195]
The booleans `SEAMS::aprepro_options::errors_fatal` and `SEAMS::aprepro_options::errors_and_warnings_fatal` don't seem to do anything. Could we make them functional or remove them?

**Comment by gsjaardema** [comment]
They are used in `packages/seacas/applications/aprepro/aprepro.C`

**Comment by ibaned** [comment]
Ah, I see. So this affects the behavior of the executable, but it doesn't change how `SEAMS::Aprepro::parse_stream` behaves.
