### ISSUE TITLE
Aprepro: Should undefined be a warning?

### ISSUE THREAD

**Issue by ibaned** [gsjaardema/seacas#196]
Would it make sense to emit a warning instead of an error when an undefined variable is encountered?

Looking at the code in `apr_util.cc` suggests this was originally desired since the function is called `undefined_error`:
```cpp
  void undefined_error(const SEAMS::Aprepro &apr, const std::string &var)
  {
    if (!apr.inIfdefGetvar) {
      apr.warning("Undefined variable '" + var + "'");
    }
    else {
      apr.inIfdefGetvar = false;
    }
  }
```

If backward compatibility is an issue, it could be made an option in `SEAMS::aprepro_options`.

If any of these changes sound acceptable I'd be happy to draft a pull request.

**Comment by gsjaardema** [comment]
There is currently some work being done by the Solid Dynamics Sierra team in this area.  Will probably be merged in a couple days and then we can take a look at it and see if it needs further work.  I will try to pull out what they are proposing and make it a PR here so you can comment.

**Comment by ibaned** [comment]
Sounds good! Thanks

**Comment by ibaned** [comment]
This was satisfied by #197
