### ISSUE TITLE
Confusing instructions for install-tpl.sh and cmake-exodus in the README.md

### ISSUE THREAD

**Issue by william76** [gsjaardema/seacas#205]
I have been looking at the README for the SEACAS scripts – the instructions for `install-tpl.sh` and the `cmake-exodus` and I’m a little confused on a few things:

1. For H5VERSION, the options are `V12`, `V110`, and `V18`. Where `V12 == 1.12.x`, `V110 == 1.10.x`, and `V18 == 1.8.x` … so why is it `V12` not `V112`? Wouldn’t that be more in-line with the labeling convention established by `V110` and `V18`?
2. Some options are YES/NO and others are ON/OFF … this is a little confusing… 
    - especially if you consider the option SHARED.  For `install-tpl.sh` it’s SHARED=YES/NO but for the cmake scripts it’s SHARED=ON/OFF … These should be synchronized to reduce confusion.
3. In the Exodus build instructions in the [README.md][1] file, it’s noted that we only need netcdf and optionally HDF5 libraries, but as far as I can see there’s no option to _NOT_ install the HDF5 libraries in `install-tpl.sh` … should there be an option to make that optional there?

[1]: https://github.com/gsjaardema/seacas/blob/master/README.md

**Comment by gsjaardema** [comment]
Yes, I need to clean that up.  I plan to make YES/ON and NO/OFF synonyms since there is a confusing mismash of these currently...   I will fix the `V12` vs `V112` as I hadn't noticed that ...

**Comment by gsjaardema** [comment]
This should all be fixed and consistent now.
