### ISSUE TITLE
undefined reference to `ex__put_homogenous_block_params'

### ISSUE THREAD

**Issue by 3rav** [gsjaardema/seacas#206]
I have this error with libexodus.a

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib/libexodus.a(ex_put_block_params.o):(.text+0x4de): undefined reference to `ex__put_homogenous_block_params'
```

**Comment by gsjaardema** [comment]
My latest commit *might* fix this.  I haven't been able to reproduce the issue, but based on the symptoms, I think that missing `extern` statements on the functions may be an issue...  Let me know if the problem persists after pulling down the latest update.
