### ISSUE TITLE
[BUG] install-tpls.sh has bad path to HDF5 1.12

### ISSUE THREAD

**Issue by william76** [gsjaardema/seacas#209]
If you give H5VERSION=V112 to `install-tpl.sh` the download will fail due to a bad path.

The path it tries to use is:

```
https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.12.0/src/hdf5-1.12.0.tar.bz2
```

but the correct path should be:

```
https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/hdf5-1.12.0/src/hdf5-1.12.0.tar.bz2
```

**Comment by gsjaardema** [comment]
This is the code for that, not sure how you are getting the `hdf5-1.10` in the path:
```
	if [ "${H5VERSION}" == "V18" ]
	then
	    wget --no-check-certificate https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-${hdf_version}.tar.bz2
	elif [ "${H5VERSION}" == "V110" ]; then
	    wget --no-check-certificate https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-${hdf_version}/src/hdf5-${hdf_version}.tar.bz2
	elif [ "${H5VERSION}" == "V112" ]; then
	    wget --no-check-certificate https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/hdf5-${hdf_version}/src/hdf5-${hdf_version}.tar.bz2
	else
	    echo 1>&2 ${txtred}Invalid HDF5 version specified: ${H5VERSION}.  Must be one of V18, V110, V112. exiting.${txtrst}
	    exit 1
	fi
```
I have also tested this in the past and it gave me the correct path...  Is your `install-tpl.sh` modified someway?

**Comment by william76** [comment]
@gsjaardema I fully wiped my build dir and reset things to the v2021 snapshot and it looks like it's doing the right thing now. We had been pulling in the 2020-08 snapshot, perhaps there was something bugged in that?

I'll close this out now :D
