### ISSUE TITLE
HDF5 libraries not in exodus test link path

### ISSUE THREAD

**Issue by tkordenbrock** [gsjaardema/seacas#216]
Using the latest master (commit 5210f6dcab87e1c6388ad50c0daab09ce967ddf9), the exodus tests fail to link on two different platforms because the HDF5 libraries are not in the link command.  The attached patch fixes this problem by partially reversing commit 27683520aeb4b08b78c0fd0fc36fd9d948b18386.  The patch also fixes a cmake if statement syntax error (``OR` instead of ||`).

I can create a PR (or 2) for these if you want me to.

[hdf5-reverse.patch.txt](https://github.com/gsjaardema/seacas/files/5992209/hdf5-reverse.patch.txt)

**Comment by gsjaardema** [comment]
Can you point me to a system where this isn't working.  If i uncomment the lines that were commented, it breaks "rebuilds" such as when a CMakeLists.txt or CMakeCache.txt changes and CMake reconfigures itself...

**Comment by gsjaardema** [comment]
This should now be working hopefully.  The changes in your patch were applied.
