### ISSUE TITLE
Exodus to XDMF converter

### ISSUE THREAD

**Issue by nathan-miller-LANL** [gsjaardema/seacas#221]
Apologies if this is less an issue and more of a question. Feel free to delete if so.

Does a converter to go from Exodus to XDMF exist in this framework? The version packaged with XDMF seems to be broken and I haven't been able to find anything through searching.

**Comment by gsjaardema** [comment]
Sorry, there is nothing at the current time.  A few years ago, we did have an XDMF reader/writer DatabaseIO object and that could be used to convert to/from Exodus, but we quit supporting it due to no one using it and it was also not keeping up with modifications to XDMF. 

It might be possible to do this via paraview, but I don't know the details of whether it is possible or how to do it.

**Comment by nathan-miller-LANL** [comment]
Thanks Greg, I suspected that was the case but I thought I would check anyway.

All the best,
Nathan

From: Greg Sjaardema ***@***.***>
Sent: Tuesday, March 30, 2021 9:11 AM
To: gsjaardema/seacas ***@***.***>
Cc: Miller, Nathan Andrew ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [gsjaardema/seacas] Exodus to XDMF converter (#221)


Sorry, there is nothing at the current time. A few years ago, we did have an XDMF reader/writer DatabaseIO object and that could be used to convert to/from Exodus, but we quit supporting it due to no one using it and it was also not keeping up with modifications to XDMF.

It might be possible to do this via paraview, but I don't know the details of whether it is possible or how to do it.

**Comment by lkuna24** [comment]
@nathan-miller-LANL Hi Nathan, have you tried the software MeshIO?  It has this capability for unstructured meshes.  In Paraview you could also try to use the 'Save Data' option.

**Comment by nathan-miller-LANL** [comment]
@lkuna24 I have tried using MeshIO but I found it wasn't able to handle timesteps properly. It very well may be that I'm just using it incorrectly though. I'll take another look at MeshIO and also look into saving the data with Paraview to see if I can't make that work. It would be nice to not have to write the converter myself!
