### ISSUE TITLE
IOSS::Decomposition passes fmt::print deprecated {:n} specifier

### ISSUE THREAD

**Issue by PhilMiller** [gsjaardema/seacas#224]
Per https://github.com/fmtlib/fmt/releases/tag/7.0.0 the `n` specifier has been deprecated in favor of `L` for alignment with `std::format`.

I recognize that seacas and IOSS bundle two copies of fmt

```
$ find ../Trilinos/ -type d -name fmt
../Trilinos/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt
../Trilinos/packages/seacas/libraries/suplib_cpp/fmt
```

But the obscurities of linking applications seems to lead to references to a common copy without the compatibility macro set.

This is raising exceptions in EMPIRE when attempting to use newer versions of other libraries that also bundle and use fmt.

**Comment by PhilMiller** [comment]
Technically, this probably brings up One Definition Rule (ODR) violations for the resulting binaries.

**Comment by gsjaardema** [comment]
I have a plan to change all `n` to `L`, but could not do it until now as there were some platforms that Trilinos was being built on that were giving errors with the more recnet versions of fmt.  Those seem to be gone now, so I am using the newest fmt versions on all platforms and should be able to switch all uses of `n` to `L` and will do that soon.

The `private_copy` version of fmt should only be being used if the Trilinos installation does not have its own copy of fmt; if that is not the case, then I probably have the configuration incorrect somewhere.  Or maybe Trilinos doesn't have a copy and EMPIRE does?  I will see if I can figure this out.

**Comment by gsjaardema** [comment]
I've put in a commit that changes all `n` to `L`, so that should be fixed now in SEACAS and will be snapshotted to Trilinos soon.  Thanks for the reminder.

**Comment by PhilMiller** [comment]
Thanks for the quick response, and I'm glad to hear we're past the transition period.

I think in our case, Trilinos does not have a copy of fmt. EMPIRE embeds a copy of DARMA-tasking/vt, which itself embeds a copy of fmt, and that's the one getting linked and called. I'm a maintainer of vt, and was working on a major update of the version embedded in EMPIRE, which brought the newer fmt with it. I realized that it was easy enough to set the compatibility flag in how ours gets compiled, with this:

```
commit d842bc36bb7ccc96eb37b96a11d6d33df540f2cd
Author: Phil Miller <pbmille@sandia.gov>
Date:   Mon Apr 26 21:53:00 2021 -0600

    Configure fmt to build with backwards compatible support for 'n' format specifier

diff --git a/TPL/vt/lib/fmt/CMakeLists.txt b/TPL/vt/lib/fmt/CMakeLists.txt
index 3899b8a..2e55df1 100644
--- a/TPL/vt/lib/fmt/CMakeLists.txt
+++ b/TPL/vt/lib/fmt/CMakeLists.txt
@@ -15,6 +15,8 @@ set(FMT_SOURCES src/format.cc)
 add_library(fmt ${FMT_SOURCES} ${FMT_HEADERS})
 add_library(fmt::fmt ALIAS fmt)
 
+target_compile_definitions(fmt PUBLIC FMT_DEPRECATED_N_SPECIFIER)
+
 target_include_directories(fmt PUBLIC
   $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>
   $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
```
