### ISSUE TITLE
exodus.py: script-with-language-extension, executable-not-elf-or-script 

### ISSUE THREAD

**Issue by nschloe** [gsjaardema/seacas#23]
The file
```
usr/bin/exodus.py
```
triggers two Debian warnings:

  * [`script-with-language-extension`](https://lintian.debian.org/tags/script-with-language-extension.html)
  * [`executable-not-elf-or-script`](https://lintian.debian.org/tags/executable-not-elf-or-script.html)

The first states that for executables, it should not matter for the user in which language it is written. That's why you won't find any `*.*` files in `/usr/bin` of your usual Linux installation.
The second is related to that, and can be fixed by adding the appropriate shebang to the top of the file, i.e.,
```
#!/usr/bin/env python
```

**Comment by gsjaardema** [comment]
I think the "real" issue is that exodus.py should not be in the bin subdirectory.   It is a python module that provides access to the exodus API, so it should probably go in the lib subdirectory, or possibly lib/python/exodus.py.  

For now, I will move to lib and if that isn't the correct location for Debian, let me know and it can be moved elsewhere

**Comment by nschloe** [comment]
Ah, I always thought that that `exodus.py` was meant to be used as an executable.

If that's not the case, it should indeed be installed somewhere else.

**Comment by gsjaardema** [comment]
exodus.py is being installed in lib instead of bin directory now.
