### ISSUE TITLE
Capability to Write Blocks from Variable (Exodus)

### ISSUE THREAD

**Issue by lkuna24** [gsjaardema/seacas#232]
Is it possible to write block IDs from a variable for an exodus file?  I've looked through `exodus` and `exomerge` but nothing obvious jumps out at me.  I've attached a sample file, that shows how I have my variable for the grain ID as 'gID', but the whole mesh is a single block.  For meshing purposes I need 'gID' to become the 'blockID'.  Can this be done?

Thanks

[Exodus_Example.tar.gz](https://github.com/gsjaardema/seacas/files/6626573/Exodus_Example.tar.gz)

**Comment by gsjaardema** [comment]
There is no function which would automatically do what you want.  You would have to read the sample file and the gid variable.  Create a histogram of the unique gid values and the number of elements for each unique gid value.  Create an exodus file with that many element blocks and then for each unique value, create an element block with the gid as the block id and then output the element connectivity for each unique value.

It should be doable with the exodus.py functions, but there is not a function that does this automatically.
