### ISSUE TITLE
Algebra segfault GCC 11

### ISSUE THREAD

**Issue by wortiz** [gsjaardema/seacas#235]
Looks to be memory related, attached ASAN and valgrind

Happens on both 2d/3d 

tested on commit 8747099253 but also segfaults on build in trilinos 13.0.1

[valgrind.txt](https://github.com/gsjaardema/seacas/files/6716499/valgrind.txt)
[asan.txt](https://github.com/gsjaardema/seacas/files/6716501/asan.txt)

**Comment by gsjaardema** [comment]
I will take a look.  It seems to run clean on gcc up to 10.3, so maybe something is different in 11.0.  Will get access to gcc-11 and see if I can reproduce.

**Comment by gsjaardema** [comment]
There is an issue in the `mdfill()` code in the supes library.  Algebra doesn't rely on this behavior, so it is OK to remove the mdfill call which will allow algebra to run.  Will still try to figure out what is wrong with `mdfill()` on gcc-11...

**Comment by wortiz** [comment]
Thanks, it works, I couldn't fine any porting guide to GCC 11 

Blot gives a similar error for ASAN 


    WRITE of size 8 at 0x7f4c20d2a7f0 thread T0
        #0 0x7f4c24aaf22c in mxrsrv_ /home/wortiz/seacas/packages/seacas/libraries/supes/mem_mgr/mxrsrv.f:100
        #1 0x7f4c24a989e1 in master.0.mdinit /home/wortiz/seacas/packages/seacas/libraries/supes/mem_mgr/mdinit.F:1539
        #2 0x7f4c24a87c87 in mdrsrv_ /home/wortiz/seacas/packages/seacas/libraries/supes/mem_mgr/mdinit.F:1478
        #3 0x409440 in blotii /home/wortiz/seacas/packages/seacas/applications/blot/blot.f:372
        #4 0x412222 in main /home/wortiz/seacas/packages/seacas/applications/blot/blot.f:1026
        #5 0x7f4c23d37b74  (/lib64/libc.so.6+0x27b74)
        #6 0x40606d in _start (/home/wortiz/seacas/bin/blot_x11+0x40606d)
    
    0x7f4c20d2a7f0 is located 16 bytes to the left of 151192-byte region [0x7f4c20d2a800,0x7f4c20d4f698)
    allocated by thread T0 here:
        #0 0x7f4c24d2e93f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
        #1 0x7f4c24a77927 in exmemy_ /home/wortiz/seacas/packages/seacas/libraries/supes/ext_lib/exmemy.c:132
        #2 0x7f4c24a9e306 in mxget_ /home/wortiz/seacas/packages/seacas/libraries/supes/mem_mgr/mxget.f:45
        #3 0x7f4c24aaef10 in mxrsrv_ /home/wortiz/seacas/packages/seacas/libraries/supes/mem_mgr/mxrsrv.f:80
        #4 0x7f4c24a989e1 in master.0.mdinit /home/wortiz/seacas/packages/seacas/libraries/supes/mem_mgr/mdinit.F:1539
        #5 0x7f4c24a87c87 in mdrsrv_ /home/wortiz/seacas/packages/seacas/libraries/supes/mem_mgr/mdinit.F:1478
        #6 0x409440 in blotii /home/wortiz/seacas/packages/seacas/applications/blot/blot.f:372
        #7 0x412222 in main /home/wortiz/seacas/packages/seacas/applications/blot/blot.f:1026
        #8 0x7f4c23d37b74  (/lib64/libc.so.6+0x27b74)

But when run with valgrind segfault before on similar code without any valgrind errors shown


    Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
    
    Backtrace for this error:
    #0  0x7fb4df807742 in ???
    #1  0x7fb4df806915 in ???
    #2  0x7fb4df4a731f in ???
    #3  0x7fb4e006e9ab in mxlong_
            at /home/wortiz/seacas/packages/seacas/libraries/supes/mem_mgr/mxlong.f:96
    #4  0x7fb4e0074927 in master.0.mdinit
            at /home/wortiz/seacas/packages/seacas/libraries/supes/mem_mgr/mdinit.F:1028
    #5  0x7fb4e006f796 in mdlong_
            at /home/wortiz/seacas/packages/seacas/libraries/supes/mem_mgr/mdinit.F:968
    #6  0x40fb1c in dbielb_
            at /home/wortiz/seacas/packages/seacas/applications/blot/dbielb.f:91
    #7  0x406c2f in blotii
            at /home/wortiz/seacas/packages/seacas/applications/blot/blot.f:429
    #8  0x40b0a5 in main
            at /home/wortiz/seacas/packages/seacas/applications/blot/blot.f:1026

If that helps at all
