### ISSUE TITLE
parmetis configuration failure due to bash script error

### ISSUE THREAD

**Issue by nwukie** [gsjaardema/seacas#247]
Running install-tpl.sh with PARMETIS=YES, the build currently fails when configuring parmetis. In TPL/parmetis/runconfigure.sh there was a change that shows up in commit fa69eb3432e6015658ed75da8fdbde048d2d2724 that seems to have invalid bash logic causing the script to fail.

FAILING
 18 MPI="${MPI:-YES}"
 19 if [ "$MPI" != "YES" ]
 20    echo "MPI Must be YES"
 21    exit 1
 22 fi

FIX: correct line 19 with valid if-then syntax
 18 MPI="${MPI:-YES}"
 19 if [ "$MPI" != "YES" ]; then
 20    echo "MPI Must be YES"
 21    exit 1
 22 fi

**Comment by gsjaardema** [comment]
Thanks.  should be fixed now.
