### ISSUE TITLE
Unique name requirement for nodesets and sidesets

### ISSUE THREAD

**Issue by loganharbour** [gsjaardema/seacas#251]
I have been told that there is a new requirement for unique naming across both nodesets and sidesets (see https://discourse.paraview.org/t/unique-name-requirement-for-nodesets-and-sidesets/8171).

In [MOOSE](https://github.com/idaholab/moose), we rely heavily on consistency in naming between nodesets and sidesets. On init, we copy sideset name mapping to node mapping.

Can someone please explain the rationality for this requirement and if there is a way around it?

**Comment by gsjaardema** [comment]
Can reopen if this is still an issue on your side, but as best I can tell, this should be working.

**Comment by loganharbour** [comment]
@gsjaardema: sorry for not following up. We're good.  https://discourse.paraview.org/t/unique-name-requirement-for-nodesets-and-sidesets/8171/5 for reference.
