### ISSUE TITLE
Fix clang -Wstrict-prototypes warnings

### ISSUE THREAD

**Issue by seanm** [gsjaardema/seacas#290]
Clang is considering making the -Wstrict-prototypes warning an error by default, see: https://discourse.llvm.org/t/rfc-enabling-wstrict-prototypes-by-default-in-c/60521

I confess I have not tried building your git master, but building [VTK](https://vtk.org) I see -Wstrict-prototypes warnings from this project.  (I suppose it's possible VTK's version is older and all such warnings are fixed in your master.)

I don't personally use seacas or that part of VTK, but though I'd at least create this ticket.

**Comment by gsjaardema** [comment]
There should be no warnings from the exodus library.

There will be warnings from the older chaco and svdi libraries, but those should not be used in vtk.

The zoltan library is used by IOSS which is used by vtk and it seems to have a few missing prototypes, but I *think* they are only in utitlity code and not in the zoltan library itself.  However, building `make Zoltan_libs` does produce multiple warnings from some include files so I need to verify whether the correct thing is getting built, or whether zoltan need some fixes to the prototypes...

**Comment by gsjaardema** [comment]
I've fixed the zoltan prototypes, so I think that all the libraries that vtk build would use should be clean with `-Wstrict-prototypes` enabled.

**Comment by seanm** [comment]
Hey wow thanks for doing this so quickly!

If you have a CI system, might I suggest enabling `-Wstrict-prototypes` on it, to keep it forever clean.

**Comment by gsjaardema** [comment]
Yes, I think my CI has a build or two where it only builds IOSS and exodus; that would be a good build to add the warning to.
