### ISSUE TITLE
Build fails on zlib

### ISSUE THREAD

**Issue by nwukie** [gsjaardema/seacas#295]
The recipe for building zlib in install-tpl.sh currently points to:

wget --no-check-certificate https://zlib.net/zlib-${zlib_version}.tar.gz

The issue is that this archive location for a specific version is not persistent. When the next version of zlib is released the archive on zlib.net is replaced with the most recent. This happened a few days ago and so the SEACAS build is currently broken for me. However, all version archives seem to be persistently accessible at https://www.zlib.net/fossils/

Recommended fix:
wget --no-check-certificate https://zlib.net/fossils/zlib-${zlib_version}.tar.gz

**Comment by gsjaardema** [comment]
Thanks.  Should be fixed in latest commit 31f2e86 (forgot to mention issue in commit message...)
