### ISSUE TITLE
SEACAS docs on gsjaardema.github.io/seacas have incorrect links

### ISSUE THREAD

**Issue by wortiz** [gsjaardema/seacas#30]
Looks like the links are case sensitive

e.g. instead of algebra linking to : http://gsjaardema.github.io/seacas/Algebra.pdf

It should link to: http://gsjaardema.github.io/seacas/algebra.pdf

There are a few others that have this issue as well.

**Comment by gdsjaar** [comment]
Thanks,  I will look into this and fix.   The fun of using a mac for this...
..Greg

--
"A supercomputer is a device for turning compute-bound problems into I/O-bound problems"

**Comment by gsjaardema** [comment]
Should be fixed now.

Thanks.

**Comment by wortiz** [comment]
Yes, thanks.
