### ISSUE TITLE
Do any of the Exodus decomposition tools support Exodus properties?

### ISSUE THREAD

**Issue by wortiz** [gsjaardema/seacas#300]
Such as those referenced by ex_get_prop and ex_put_prop

This is used by https://www.sandia.gov/files/cubit/15.8/help_manual/WebHelp/finite_element_model/exodus/nodesets_and_sidesets.htm#associativitydata

And is useful for remeshing using Cubit.

Both the decomp and io_shell tools seem to skip writing these properties, so they are not there after an epu -auto

**Comment by gsjaardema** [comment]
Sorry, no.  The properties in ex_get_prop and ex_put_prop were never really used and so support for those by any of the SEACAS tools is pretty much nonexistant.

I'm not sure why CUBIT decided to use those...

**Comment by wortiz** [comment]
Ok, thanks.
