### ISSUE TITLE
Potential Ioss_Utils symbol conflicts

### ISSUE THREAD

**Issue by mathstuf** [gsjaardema/seacas#301]
`Ioss::DEBUG()` is a convenience method to get a stream for debugging. However, `DEBUG` is a preprocessor symbol used by` windows.h` at times (I can't remember the details, but we've had to rename some `enum` items because of this). I think a better name for this should be used at least. I suspect that `WARNING` is also ripe for conflicts with libraries using `#define` for log levels.

**Comment by gsjaardema** [comment]
`Ioss::DEBUG()` has been changed to `Ioss::DebugOut()` and `Ioss::WARNING()` has been changed to `Ioss::WarnOut`.  I left `Ioss::OUTPUT()` alone.

**Comment by gsjaardema** [comment]
I think this is addressed now.   Please reopen if there is still an issue.
