### ISSUE TITLE
install the SEACAS package on ubuntu 14.04

### ISSUE THREAD

**Issue by gsjaardema** [gsjaardema/seacas#34]
Hi Greg,

When i try to install the SEACAS package , I get the error message as below.

I follow the instruction on https://github.com/gsjaardema/seacas#get-the-sources

![image](https://cloud.githubusercontent.com/assets/897294/13753499/d7f62904-e9d8-11e5-962f-9a3e96d24f9e.png)

any ideas?

Thanks .

iKnowledge

Peter Chen 

e: pchen@iknowledgesolutions.com

**Comment by gsjaardema** [comment]
@nschloe Any ideas?  

Peter responded that he did do the repository add and update prior to the install.

**Comment by nschloe** [comment]
There's no package by the name `seacas`. Check out
```
$ apt search seacas
Sorting... Done
Full Text Search... Done
libseacas-dev/wily 2.0~20160314030001-wily1 amd64
  processing tools and applications for finite element analysis

libseacas0/wily 2.0~20160314030001-wily1 amd64
  processing tools and applications for finite element analysis

seacas-bin/wily 2.0~20160314030001-wily1 amd64
  processing tools and applications for finite element analysis
```

**Comment by gsjaardema** [comment]
OK.  I will update the README.md file to specify that users should install
seacas-bin instead of just seacas.  They can also install libseacas-dev and
libseacas0.

..Greg
