### ISSUE TITLE
SEACASIoss optionally uses but does not declare a TPL dependency on ParMETIS

### ISSUE THREAD

**Issue by bartlettroscoe** [gsjaardema/seacas#51]
While working on trilinos/Trilinos#158, I noticed that SEACAS optionally uses ParMETIS but is not properly declaring its dependence on the TriBITS TPL ParMETIS.  You can see this by looking at:

```
$ cd Trilinos/packages/seacas/
$  find . -name CMakeLists.txt -exec grep -nHi parmetis {} \;
./libraries/ioss/src/CMakeLists.txt:16:IF (${PROJECT_NAME}_ENABLE_ParMETIS)
./libraries/ioss/src/CMakeLists.txt:17:  SET(PARMETIS_LIB "parmetis")
./libraries/ioss/src/CMakeLists.txt:19:  ADD_DEFINITIONS(-DNO_PARMETIS_SUPPORT)
./libraries/ioss/src/CMakeLists.txt:41:  ${PARMETIS_LIB}
./libraries/ioss/src/cgns/CMakeLists.txt:12:IF (${PROJECT_NAME}_ENABLE_ParMETIS)
./libraries/ioss/src/cgns/CMakeLists.txt:13:  SET(PARMETIS_LIB "parmetis")
./libraries/ioss/src/cgns/CMakeLists.txt:15:  ADD_DEFINITIONS(-DNO_PARMETIS_SUPPORT)
./libraries/ioss/src/exo_par/CMakeLists.txt:11:IF (${PROJECT_NAME}_ENABLE_ParMETIS)
./libraries/ioss/src/exo_par/CMakeLists.txt:12:  SET(PARMETIS_LIB "parmetis")
./libraries/ioss/src/exo_par/CMakeLists.txt:14:  ADD_DEFINITIONS(-DNO_PARMETIS_SUPPORT)
./libraries/ioss/src/exo_par/CMakeLists.txt:31:  DEPLIBS Ioss Ioex ${PARMETIS_LIB}
```

There are a few problems with this approach:

1. The SEACASIoss CMakeLists.txt files have to manually pull in the ParMETIS libs.  If you list the TPL dependence in Dependencies.cmake, then those libs will be included automatically when the TPL is enabled.

2. SEACASIoss assumes the library name is "parametis" but that may not always be the case on every system.  Letting the TriBITS TPL system handle this allows the user to point to whatever libraries that need to that supply ParMETIS.

3. A user can't disable support for just ParMETIS in SEACAS if there is some problem on some platform.  For example, other Trilinos packages also optionally use ParMETIS like Zoltan, Zoltan2, Amesos, Amesos2, ML and ShyLU.  Let's say that there is some problem building SEACAS with the certain version of ParMETIS installed on some platform but the other packages build with this version of ParMETIS just fine.  In this case, the user may not need to use ParMETIS with SEACAS but they do need ParMETIS with a subset of these other packages.  By having SEACAS properly declare an optional dependency on ParMETIS, the user can configure with `-DSEACASIoss_ENABLE_ParMETIS=OFF` and then they can still build and do what they need.  With the current setup of SEACASIoss, they can't do that.

To fix this:

1. List ParaMETIS in the file seacas/libraries/ioss/cmake/Dependencies.cmake in the list LIB_OPTIONAL_LIBS
2. Remove the CMakeList.txt code that directly adds the library "parametis"

For more documentation on optional TPLs, see:

* https://tribits.org/doc/TribitsDevelopersGuide.html#how-to-add-a-new-tribits-tpl-dependency
* https://tribits.org/doc/TribitsDevelopersGuide.html#package-name-enable-optional-dep-tpl-name
* https://tribits.org/doc/TribitsDevelopersGuide.html#support-for-optional-se-package-tpl-can-be-explicitly-disabled

**Comment by bartlettroscoe** [comment]
@gsjaardema, I can fix this and create a PR if you would like.  The only thing that I need to know is how I can be sure that ParMETIS is actually being used in SEACASIoss.  Is there some test in SEACAS that I can look at that will prove that ParMETIS is being used and is performing correctly?

**Comment by gdsjaar** [comment]
OK, thanks.  I have committed this to the seacas repository and will sync over to Trilinos soon.
..Greg


--
"A supercomputer is a device for turning compute-bound problems into I/O-bound problems”

**Comment by gsjaardema** [comment]
I will add a test.
..Greg

On Fri, Jul 1, 2016 at 9:13 AM, Roscoe A. Bartlett <notifications@github.com
