### ISSUE TITLE
Errors due to missing "-lcurl" linker flag

### ISSUE THREAD

**Issue by aprokop** [gsjaardema/seacas#63]
I think SEACAS depends on curl, but does not automatically add `-lcurl` during compilation. For instance, I was getting the following errors
```
Linking Fortran executable gen3d
../../libraries/exodus/libexodus.so.12.9: undefined reference to `curl_easy_perform'
../../libraries/exodus/libexodus.so.12.9: undefined reference to `curl_easy_getinfo'
../../libraries/exodus/libexodus.so.12.9: undefined reference to `curl_easy_init'
../../libraries/exodus/libexodus.so.12.9: undefined reference to `curl_easy_strerror'
../../libraries/exodus/libexodus.so.12.9: undefined reference to `curl_version_info'
../../libraries/exodus/libexodus.so.12.9: undefined reference to `curl_easy_cleanup'
../../libraries/exodus/libexodus.so.12.9: undefined reference to `curl_easy_setopt'
collect2: error: ld returned 1 exit status
```
I have a proper `/usr/lib64/libcurl.so` but it was not picked up because of the missing `-lcurl` for executable linking. 

The current workaround for me is to add the following to my CMake configuration:
```cmake
-D CMAKE_EXE_LINKER_FLAGS="-lcurl"
```

**Comment by gdsjaar** [comment]
It only depends on curl if your netcdf library depends on curl.  We recommend configuring netcdf such that dap and cdmremote are disabled.  This is where the curl dependency is coming from.  If you have a shared netcdf library, then those dependencies should be added automatically by the shareable library system.

I can look at modifying my FindNetcdf.cmake file to automatically pick up the additional dependencies…
..Greg

--
"A supercomputer is a device for turning compute-bound problems into I/O-bound problems”

**Comment by aprokop** [comment]
@gdsjaar Thanks, I'm playing around with spack and I think I hit this corner case: I'm compiling netcdf without disabling cmdremote, but using static netcdf library in overall shared build. I'll try disabling `dap` and `cmdremote` first, as this seems much easier.

**Comment by aprokop** [comment]
I can confirm that with disabled `dap` and `cmdremote` the `-lcurl` flag is not necessary.

I am closing the issue with a remark that ideally we would detect this situation during the configure stage but this may be complicated.

**Comment by gsjaardema** [comment]
Thanks.

**Comment by tedtoal** [comment]
Can you please explain HOW one goes about disabling dap and cmdremote?

**Comment by gsjaardema** [comment]
Take a look at `TPL/netcdf/runcmake.sh` or `TPL/netcdf/runconfigure.sh`.

For CMake, it is `-DENABLE_DAP:BOOL=OFF`.   For configure it is `--disable-dap`
