### ISSUE TITLE
error: unknown type name ‘ZOLTAN_ID_PTR’

### ISSUE THREAD

**Issue by nschloe** [gsjaardema/seacas#68]
I'm getting build errors of the kind
```
In file included from /home/nschloe/software/seacas/source-upstream/packages/zoltan/src/tpls/parmetis_interface.h:53:0,
                 from /home/nschloe/software/seacas/source-upstream/packages/zoltan/src/tpls/parmetis_interface.c:52:
/home/nschloe/software/seacas/source-upstream/packages/zoltan/src/tpls/third_library_const.h:249:31: error: unknown type name ‘ZOLTAN_ID_PTR’
```
for a while now. One configuration to reproduce the error:
```
cmake  \
  -DBUILD_SHARED_LIBS:BOOL=ON \
  -DSEACASProj_ENABLE_ALL_PACKAGES:BOOL=ON \
  -DSEACASProj_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
  -DSEACASProj_ENABLE_SECONDARY_TESTED_CODE:BOOL=ON \
  -DSEACASProj_ENABLE_TESTS:BOOL=ON \
  -DSEACASProj_USE_GNUINSTALLDIRS:BOOL=ON \
  -DHDF5_ROOT:PATH=/usr \
  \
  -DTPL_ENABLE_CGNS:BOOL=ON \
  -DTPL_ENABLE_Matio:BOOL=ON \
  -DTPL_ENABLE_METIS:BOOL=ON \
  -DTPL_ENABLE_ParMETIS:BOOL=ON \
  -DTPL_ENABLE_Netcdf:BOOL=ON \
  -DTPL_ENABLE_MPI:BOOL=OFF \
  -DTPL_ENABLE_Pamgen:BOOL=OFF \
  -DTPL_ENABLE_X11:BOOL=OFF \
  -DTPL_ENABLE_Zlib:BOOL=ON \
  \
  ../source-upstream/
```
(Can probably be shortened.)

**Comment by gsjaardema** [comment]
One issue is that ParMETIS should not be enabled unless MPI=ON.  Not sure if that is causing the issue or not.  

But, build system should either issue warning that this is not supported, or should ignore the parmetis setting for a serial build.

**Comment by nschloe** [comment]
The ParMETIS setting is _not_ the culprit. I'm getting the same error with
```
cmake  \
  -DBUILD_SHARED_LIBS:BOOL=ON \
  -DSEACASProj_ENABLE_ALL_PACKAGES:BOOL=ON \
  -DSEACASProj_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
  -DSEACASProj_ENABLE_SECONDARY_TESTED_CODE:BOOL=ON \
  -DSEACASProj_ENABLE_TESTS:BOOL=ON \
  -DSEACASProj_USE_GNUINSTALLDIRS:BOOL=ON \
  -DHDF5_ROOT:PATH=/usr \
  \
  -DTPL_ENABLE_CGNS:BOOL=ON \
  -DTPL_ENABLE_Matio:BOOL=ON \
  -DTPL_ENABLE_METIS:BOOL=ON \
  -DTPL_ENABLE_Pamgen:BOOL=OFF \
  -DTPL_ENABLE_ParMETIS:BOOL=OFF \
  -DTPL_ENABLE_Netcdf:BOOL=ON \
  -DTPL_ENABLE_MPI:BOOL=OFF \
  -DTPL_ENABLE_X11:BOOL=OFF \
  -DTPL_ENABLE_Zlib:BOOL=ON \
  \
  ../source-upstream/
```

**Comment by nschloe** [comment]
Apparently, _Metis_ is causing the trouble:
```
cmake  \
  -DBUILD_SHARED_LIBS:BOOL=ON \
  -DSEACASProj_ENABLE_ALL_PACKAGES:BOOL=ON \
  -DTPL_ENABLE_METIS:BOOL=ON \
  -DTPL_ENABLE_MPI:BOOL=OFF \
  ../source-upstream/
```

**Comment by gdsjaar** [comment]
I had seen something similar awhile ago and I thought Karen Devine and I had fixed the issue; obviously it is still occurring.  I will take a look.
..Greg

--
"A supercomputer is a device for turning compute-bound problems into I/O-bound problems”

**Comment by gsjaardema** [comment]
OK, this should be fixed now.  I had discussed fixing this with the zoltan developers and they provided a fix in Trilinos, but it never got snapshotted into SEACAS.  I did the snapshot today and confirmed that the build errors shown above have been eliminated.  There are still a few warnings, but the build should succeed.

**Comment by nschloe** [comment]
Sounds good!

I guess the travis tests didn't catch on to this because of `-DTPL_ENABLE_METIS:BOOL=OFF`. Probably worthwhile setting it to `ON`.
