### ISSUE TITLE
BUILD_SHARED_LIBS not fully respected

### ISSUE THREAD

**Issue by nschloe** [gsjaardema/seacas#69]
When configuring with
```
cmake  \
  -DBUILD_SHARED_LIBS:BOOL=ON \
  -DSEACASProj_ENABLE_ALL_PACKAGES:BOOL=ON \
  -DTPL_ENABLE_MPI:BOOL=OFF \
  ../source-upstream/
```
not all libraries are built dynamically. Check out
```
[ 37%] Linking C static library libexodus.a
[ 55%] Linking C static library libchaco.a
[ 55%] Linking C shared library libsuplib_c.so
[ 57%] Linking Fortran shared library libsupes.so
```

**Comment by gdsjaar** [comment]
In seacas, it will build both a static and shared version of the exodus library.  Chaco is explicitly only built as a static library to fix some build issues we were having.
..Greg

--
"A supercomputer is a device for turning compute-bound problems into I/O-bound problems”

**Comment by nschloe** [comment]
> In seacas, it will build both a static and shared version of the exodus library.

Ah, funny. Typically if you're building shared and static versions of a library, you'll also want different compile objects for the object files involved (e.g., `-fPIC` and friends). Looking at the CMake code, I see
```cmake
if (${CMAKE_PROJECT_NAME} STREQUAL "SEACASProj")
   # Many users of the SEACAS installations still want a static exodus library...
   if (BUILD_SHARED_LIBS)
      ADD_LIBRARY(
              exodus_static
              STATIC
              ${SOURCES} ${DEP_SOURCES}
      )
      set_target_properties(exodus_static PROPERTIES OUTPUT_NAME exodus)
      INSTALL(TARGETS exodus_static DESTINATION ${CMAKE_INSTALL_PREFIX}/lib)
   endif(BUILD_SHARED_LIBS)

   # For backwards compatability, the C exodus library was called libexoIIv2c.a
   # Create a symbolic link from libexodus.a to libexoIIv2c.a -- do only for static lib
   InstallSymLink(libexodus.a ${CMAKE_INSTALL_PREFIX}/lib/libexoIIv2c.a)
endif()
```
so if `BUILD_SHARED_LIBS`, two library versions are built. Not sure if this is the right thing to do. After all, anyone gets static libraries if you don't specify `BUILD_SHARED_LIBS` (or set it to `FALSE`).

In any case, this is your call. Feel free to close.

**Comment by gsjaardema** [comment]
It is historical -- there are many users here that always want to link with a static exodus library.  Instead of building two separate installations, we build both static and shared exodus if shared libs are requested.

There are two different compile objects for the shared and static exodus library.  If you watch the build, you will see it doing two separate compilations -- one for the static library and one for the objects in the shared library.
