### ISSUE TITLE
exodus_for/CMakeLists.txt not setting search path for exodusII.h

### ISSUE THREAD

**Issue by twhitehead** [gsjaardema/seacas#72]
Noticed that the *[exodus_for/CMakeLists.txt](https://github.com/gsjaardema/seacas/blob/793152b8749f1e80aa683e7f2c99e701078cf413/packages/seacas/libraries/exodus_for/CMakeLists.txt
)* doesn't add the *[exodus/include](https://github.com/gsjaardema/seacas/tree/793152b8749f1e80aa683e7f2c99e701078cf413/packages/seacas/libraries/exodus/include
)* search path despite it being required by the [*exodus_for/src/exo_jack.c* source file to include *exodusII.h*](https://github.com/gsjaardema/seacas/blob/793152b8749f1e80aa683e7f2c99e701078cf413/packages/seacas/libraries/exodus_for/src/exo_jack.c#L50).

(note that I haven't actually verified I get this error in this repository, rather it was something I came across while compiling the version petsc packages up and went here to see how it had been addressed and as far as I can tell it hasn't)

**Comment by gsjaardema** [comment]
SEACAS Uses TriBITs which is a package that comes between raw cmake and the project code.  There should be a exodus_for/cmake/Dependencies.cmake which specifies that exodus_for depends on exodus and therefore sets up the correct include paths to find exodusII.h

I think it is doing the right thing.

**Comment by twhitehead** [comment]
Thanks for the clarification. :smile:
