### ISSUE TITLE
Add nodal variable to exodus file with exodus.py

### ISSUE THREAD

**Issue by acochrane** [gsjaardema/seacas#73]
I'm trying to add a nodal variable to an exodus file that has pre-existing nodal variables with the exodus python wrapper.

It appears that the "set_node_variable_number" function can only succeed when no nodal variable files exist in the file.

The traceback follows:
`File "/home/acochrane/goma/TPL_exp/seacas/lib/exodus.py", line 4956, in add_variables exo.set_node_variable_number(n_vars)`
`File "/home/acochrane/goma/TPL_exp/seacas/lib/exodus.py", line 905, in set_node_variable_number self.__ex_put_variable_param(ndType, number)`
`File "/home/acochrane/goma/TPL_exp/seacas/lib/exodus.py", line 4337, in __ex_put_variable_param raise Exception, ("ERROR: ex_put_variable_param had problems. This can only be called once per varType.")`
`Exception: ERROR: ex_put_variable_param had problems. This can only be called once per varType.`

Intermediate solution is to:

1.  create a new file with the resulting number of variables
2.  copy the old variables in
3.  copy the new variable in

**Comment by gsjaardema** [comment]
Your intermediate solution is the correct way to handle this.  It is not possible to modify the number of variables in an existing file; you must create a new file with the correct number of variables and then copy the old variables and add the new variables to the new file.

**Comment by gsjaardema** [comment]
There is a copyTransfer routine that may do what you want:

```
def copyTransfer(fromFileName, toFileName, array_type='ctype', \
    additionalGlobalVariables=[], additionalNodalVariables=[], \
    additionalElementVariables=[], additionalElementAttributes=[]):
  """
    This function creates an exodus file toFileName and copies
    everything from exodus file fromFileName returning a file handle
    to toFileName.

    Additional space is allocated for additionalGlobalVariables,
    additionalNodalVariables and additionalElementVariables if
    specified.

    additionalGlobalVariables: list of global variable names to add.

    additionalNodalVaraibles: list of nodal variable names to add.

    additionalElementVariables: should be a list of element variable
    names to add to all blocks or tuples (name, blkIds) where name is
    the element variable to add and blkIds is a list of blkIds to add
    it to.
                                
    additionalElementAttributes: list of element attribute names to
    add to all blocks or tuples ( name, blkIds ) where name is the
    element attribute to add and blkIds is a list of blkIds to add it
    to.  Usage:

    fromFileName = "input.e"
    toFileName = "output.e"
    addGlobalVariables = [] ## Do not add any new global variables
    addNodeVariables = ["node_dummy1", "node_dummy2"] ## Add node_dummy1 and node_dummy2 as new node variables
    addElementVariables = [ ("elem_dummy1", [1, 2, 3]), "elem_dummy2" ] ## Add elem_dummy1 on blkIds 1, 2, 3 and elem_dummy2 on all blocks
    addElementAttributes = [ ("elem_attr_dummy1",[1,2,3]), "elem_attr_dummy2" ] ## Add elem_attr_dummy1 on blkIds 1,2,3 and elem_attr_dummy2 on all blocks

    toFileHandle = copyTranfer(fromFileName,toFileName,addGlobalVariables,addNodeVariables,addElementVariables,addElementAttributes)

    ## Fill in new variables

    toFileHandle.close()

  """
```
