### ISSUE TITLE
Error when building without CGNS

### ISSUE THREAD

**Issue by wortiz** [gsjaardema/seacas#77]
TPL_ENABLE_CGNS might not be turning on the right defines

I get the following error when trying to build without CGNS (and without MATIO)

    In file included from /home/wortiz/projects/goma/libraries/seacas/packages/seacas/libraries/ioss/src/Ioss_DatabaseIO.C:42:
    /home/wortiz/projects/goma/libraries/seacas/packages/seacas/libraries/ioss/src/Ioss_StructuredBlock.h:46:10: fatal error: 
          'cgnstypes.h' file not found
    #include <cgnstypes.h>
             ^~~~~~~~~~~~~
    1 error generated.
    packages/seacas/libraries/ioss/src/CMakeFiles/Ioss.dir/build.make:158: recipe for target 'packages/seacas/libraries/ioss/src/CMakeFiles/Ioss.dir/Ioss_DatabaseIO.C.o' failed
    make[2]: *** [packages/seacas/libraries/ioss/src/CMakeFiles/Ioss.dir/Ioss_DatabaseIO.C.o] Error 1
    CMakeFiles/Makefile2:4520: recipe for target 'packages/seacas/libraries/ioss/src/CMakeFiles/Ioss.dir/all' failed

But my cmake was configured with CGNS off:

    $ cmake -LA -N .. |grep TPL_ENABLE_CGNS
    TPL_ENABLE_CGNS:BOOL=OFF

Changes to cmake-config:

    $ git diff
    diff --git a/cmake-config b/cmake-config
    index a811b6c..36aff94 100755
    --- a/cmake-config
    +++ b/cmake-config
    @@ -31,8 +31,8 @@ INSTALL_PATH=${ACCESS}
     ### subdirectories of the specified paths.
     ### For example, netcdf.h should be in ${NETCDF_PATH}/include
     HAVE_NETCDF=ON
    -HAVE_MATIO=ON
    -HAVE_CGNS=ON
    +HAVE_MATIO=OFF
    +HAVE_CGNS=OFF
     
     NETCDF_PATH=${ACCESS}
     MATIO_PATH=${ACCESS}

**Comment by gsjaardema** [comment]
This should be fixed now.  There was some missing logic in the CMakeLists.txt file in the ioss/src subdirectory.  It should be correct now.

**Comment by wortiz** [comment]
ejoin also requires that define: Moving your add_definition from Ioss/src to the packages/seacas/CMakeLists.txt fixes the define issue for me

    In file included from /home/wortiz/projects/goma/libraries/seacas/packages/seacas/applications/ejoin/EJoin.C:61:
    In file included from /home/wortiz/projects/goma/libraries/seacas/packages/seacas/libraries/ioss/src/Ioss_SubSystem.h:59:
    /home/wortiz/projects/goma/libraries/seacas/packages/seacas/libraries/ioss/src/Ioss_StructuredBlock.h:46:10: fatal error: 
          'cgnstypes.h' file not found
    #include <cgnstypes.h>

**Comment by gsjaardema** [comment]
This should work now.  Thanks for reporting.
.. greg

**Comment by wortiz** [comment]
Build works without cgns now with latest changes.

Thanks.
