### ISSUE TITLE
cmake-config has no closing string literal

### ISSUE THREAD

**Issue by daniellivingston** [gsjaardema/seacas#79]
In the `cmake-config` file, starting on line 101, there is an open string literal without a closing string literal:

    if [ "HAVE_DATA_WAREHOUSE" == "ON" ]
    then
        DW_SYMBOLS="-DSEACASIoss_ENABLE_DataWarehouse=${HAVE_DATAWAREHOUSE} \
                    -DTPL_ENABLE_DataWarehouse:BOOL=${HAVE_DATAWAREHOUSE}   \
                    -DDataWarehouse_LIBRARY_DIRS:PATH=${DataWarehouse_PATH}/lib     \
                    -DDataWarehouse_INCLUDE_DIRS:PATH=${DataWarehouse_PATH}/include \
    fi

Note that `DW_SYMBOLS="` has no closing `"`. Bash throws an error and quits compilation.

**Comment by gsjaardema** [comment]
Sorry, i got interrupted  during this change and somehow added this file to the intended commit.  I will try to be more careful next time...

**Comment by daniellivingston** [comment]
No worries, thanks for the fix!
