### ISSUE TITLE
CMake Error: -D must be followed with VAR=VALUE

### ISSUE THREAD

**Issue by daniellivingston** [gsjaardema/seacas#80]
Thrown error:

    ../cmake-config
    CMake Error: -D must be followed with VAR=VALUE.
    CMake Error: Problem processing arguments. Aborting.

    ../cmake-config: line 133: -D: command not found

Relevant line in `cmake-config`: 

    131:  -D TPL_ENABLE_MPI:BOOL=${MPI} \
    132:  -D TPL_ENABLE_Pamgen:BOOL=OFF \
    133:  -D 
    134:  -D TPL_ENABLE_Pthread:BOOL=${THREADSAFE_IO_LIBS} \

**Comment by gsjaardema** [comment]
Sorry, I accidentally committed that file while I was in the middle of a change.  Should be fixed now.  Thanks for catching this.

**Comment by daniellivingston** [comment]
Thanks for the fix!
