### ISSUE TITLE
Fortran build warning / remark

### ISSUE THREAD

**Issue by mhoemmen** [gsjaardema/seacas#85]
```
.../seacas/libraries/supes/fre_fld/ffistr.f(283): remark #8577: The scale factor (k) and number of fractional digits (d) do not have the allowed combination of either -d < k <= 0 or 0 < k < d+2. Expect asterisks as output.
```

**Comment by gsjaardema** [comment]
This is an INPUT, so in theory it should be ok, but the intel site recommends replacing E32.0 with F32.0 to avoid the remark.  That has been done, so this should be fixed.  It will take a little while to sync over to Trilinos

**Comment by mhoemmen** [comment]
Thanks @gsjaardema !  Does that mean we should close this issue?

**Comment by gsjaardema** [comment]
Yes, I think it can be closed.
