### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_ex_create_int", referenced from: _main in main.oError when trying the ex_create function  

### ISSUE THREAD

**Issue by maxiaodage** [gsjaardema/seacas#88]
Below is a simple main function to test the ex_create_int api function from the exodus libarary, howver I got the error , and it is really strange i "_ex_create_int" undefined symbols, I am suspecting it is this underscore in front of ex_create_int is giving me problem , I also try the other function ex_open , ex_close , and all these giving me the similar message . 

#include <iostream>
#include "exodusII.h"
 using namespace std;

int main() {

   float version;
   int CPU_word_size = sizeof(float);
   int IO_word_size = 8;
   int exoid= ex_create("./test.exo",
                      EX_CLOBBER,
                      &CPU_word_size,
                      &IO_word_size);
}

_Error Message :_ 
g++ main.o -o output -fopenmp
Undefined symbols for architecture x86_64:
  "_ex_create_int", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [output] Error 1

**Comment by gsjaardema** [comment]
You need to also link to the exodus library.  Something like:
```
g++ main.o -o output -fopenmp -lexodus -lnetcdf
```
You may need to tell the linker where to find the library.  You would use the "-L{path}" option. For example:
```
g++ main.o -o output -fopenmp -L/path/to/lib -lexodus -lnetcdf
```

**Comment by gsjaardema** [comment]
No further feedback.

**Comment by maxiaodage** [comment]
Problem solved , thank you
