### ISSUE TITLE
Change in mapvar behavior (appears to be broken)

### ISSUE THREAD

**Issue by wortiz** [gsjaardema/seacas#90]
Running mapvar built with current seacas appears to be broken no values are actually mapped, the nodal variable does appear in the interpolated mesh.

Mapvar does work with trilinos 12.10.1 version 

My seacas is built with shared libraries while seacas built through trilinos is built with static libraries if that changes anything.

Here are 4 element mapping to 8 element testfiles that fail on my machine

[mapvar_mesh_test.tar.gz](https://github.com/gsjaardema/seacas/files/1528295/mapvar_mesh_test.tar.gz)

Running mapvar with:

mapvar tmp
run

The current seacas version does not appear to print out normal mapvar information while the trilinos version appears to work fine

**Comment by gsjaardema** [comment]
Not sure what is wrong...  I can run on my Mac SEACAS install and I get the `tmp.int` with a single nodal variable as should be expected.  The `tmp.o` also has the expected output.

```
 Database:  tmp.int

 cubit(square.e): 12/04/2017: 11:13:03

 Number of coordinates per node       =         2
 Number of nodes                      =        25
 Number of elements                   =        16
 Number of element blocks             =         1

 Number of nodal point sets           =         5
    Length of node list               =        21
    Length of distribution list       =        21
 Number of element side sets          =         4
    Length of element list            =        16
    Length of node list               =        32
    Length of distribution list       =        32

 Number of coordinate frames          =         0

 Number of global variables           =         0
 Number of variables at each node     =         1
 Number of variables at each element  =         0
 Number of variables at each nodeset  =         0
 Number of variables at each sideset  =         0

 Number of time steps on the database =         1
```

**Comment by wortiz** [comment]
Do you get actual mapped values for the nodal variable? I get the nodal variable in my output but the values all appear to be 0 for the current seacas version

**Comment by gsjaardema** [comment]
OK, sorry I didn't check the values.

It should be fixed now.  We made a change to exodus library that verified that a timestep was defined prior to writing data to the step.  Mapvar was not following that and tripped the error, but was not checking for errors, so it got lost.

Should be fixed now; sorry for the trouble and incomplete debugging.

**Comment by wortiz** [comment]
Looks like it works now.

Thanks.
