### ISSUE TITLE
You have a CMake bug

### ISSUE THREAD

**Issue by knepley** [gsjaardema/seacas#91]
Here is the fix (from 840b0e38a7390ecd53614f68b9b5def6b4a3fbd2),

diff --git a/cmake/tribits/common_tpls/find_modules/FindNetCDF.cmake b/cmake/tri
index a71d387..b88c4d0 100644
--- a/cmake/tribits/common_tpls/find_modules/FindNetCDF.cmake
+++ b/cmake/tribits/common_tpls/find_modules/FindNetCDF.cmake
@@ -175,7 +175,7 @@ else(NetCDF_LIBRARIES AND NetCDF_INCLUDE_DIRS)
         if(meta_path)
           # Search meta for NetCDF Version...
           file(STRINGS "${meta_path}/netcdf_meta.h" netcdf_ver_string REGEX "NC
-          string(REGEX REPLACE "[^0-9\.]" "" netcdf_version "${netcdf_ver_strin
+          string(REGEX REPLACE "[^0-9\\.]" "" netcdf_version "${netcdf_ver_stri
 
           # Search meta for NC_HAS_PARALLEL setting...
           file(STRINGS "${meta_path}/netcdf_meta.h" netcdf_par_string REGEX "NC

**Comment by gsjaardema** [comment]
I seem to get the correct behavior for the current REGEX REPLACE.  Are you seeing a failure that caused you to suggest this patch?

**Comment by knepley** [comment]
Yes

**Comment by knepley** [comment]
Did you push the fix?

  Thanks,

    Matt

@jedbrown

**Comment by gsjaardema** [comment]
I didn't push the fix since I haven't been able to reproduce the problem it is meant to solve and have had no other instances of anyone having the problem.  If you can show me the output indicating the problem and what system(s) it is appearing on, I will revisit.
