### ISSUE TITLE
Please don't install third-party executables, they might conflict with others

### ISSUE THREAD

**Issue by yurivict** [gsjaardema/seacas#92]
Please see the list of executables that Trilinos installs, and the comments there:
https://github.com/trilinos/Trilinos/issues/2097#issuecomment-354563939

You should at least rename them to reflect the fact that you installed them. Ex. ```seacas-sphgen```.

**Comment by gsjaardema** [comment]
Not sure I understand fully.  The 'sphgen' executable has existed in SEACAS for about 20 years so not sure why it is correct for another package to use the name and I have to change my usage?  I'm willing to work to get this fixed, but not sure of who decides which name is correct and which is wrong?

**Comment by gsjaardema** [comment]
No response for several months...
